project:
  type: website
  output-dir: docs

website:
  title: "Work From Home in Illinois"
  navbar:
    left:
      - href: WFH_geographicComparison.qmd
        text: "Data Prep"
      - WFH_Models.qmd
      
format:
  html:
    theme: cosmo
    toc: true

