<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Work From Home: Who Can and Who Does?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="WorkFromHome_files/libs/clipboard/clipboard.min.js"></script>
<script src="WorkFromHome_files/libs/quarto-html/quarto.js"></script>
<script src="WorkFromHome_files/libs/quarto-html/popper.min.js"></script>
<script src="WorkFromHome_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="WorkFromHome_files/libs/quarto-html/anchor.min.js"></script>
<link href="WorkFromHome_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="WorkFromHome_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="WorkFromHome_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="WorkFromHome_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="WorkFromHome_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Work From Home: Who Can and Who Does?</h1>
<p class="subtitle lead">Using ACS &amp; O*NET Data</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="getting-data" class="level1">
<h1>Getting Data</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reldist)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pollster)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(labelled)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(weights)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tigris)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ipumsr)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="acs-data-notes" class="level1">
<h1>ACS data Notes</h1>
<ul>
<li><p>INCWAGE is topcoded only at the 99.5th percentile within a state. So almost ALL obs should be close their actual income.</p>
<ul>
<li>Incwage coding procedure <a href="https://usa.ipums.org/usa-action/variables/INCWAGE#editing_procedure_section">link</a></li>
<li>1-7$ is turned to $4.</li>
<li>Between 8 and 999, rounded to nearest $10.</li>
<li>Between 1000 and 49999 rounded to nearest 100</li>
<li>over 50,000 rounded to nearest 1000</li>
</ul></li>
<li><p>INCTOT includes self-employment income, INCWAGE does not.</p>
<ul>
<li>Some industries (e.g.&nbsp;farming) may not be included in sample if using INCWAGE. Does that matter?</li>
<li>Bottom coded at -$19,988, is not top coded</li>
</ul></li>
<li><p>INCEARN includes salaries, wages, and business/farm income. Use this one I think</p>
<ul>
<li><p>INCEARN is made from summing INCWAGE, INCBUS, and INCFARM</p></li>
<li><p>INCEARN is not itself topcoded, but some of the other variables may be, especially for early years of data collection (which don’t apply to us)</p></li>
</ul></li>
</ul>
<section id="year-data" class="level2">
<h2 class="anchored" data-anchor-id="year-data">2021 1-Year Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>ddi <span class="ot">&lt;-</span> <span class="fu">read_ipums_ddi</span>(<span class="st">"usa_00008.xml"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_ipums_micro</span>(ddi) <span class="co"># 747787 observations before any filtering</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Use of data from IPUMS USA is subject to conditions including that users should
cite the data appropriately. Use command `ipums_conditions()` for more details.</code></pre>
</div>
</div>
</section>
<section id="year-acs-2016-2021" class="level2">
<h2 class="anchored" data-anchor-id="year-acs-2016-2021">2021 5-Year ACS (2016-2021)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tigris)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ipumsr)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># PUMA shapefiles</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>pumasIL <span class="ot">&lt;-</span> <span class="fu">pumas</span>(<span class="st">"IL"</span>, <span class="at">cb=</span>T, <span class="at">year=</span><span class="dv">2019</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co">#county shapefiles</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>countyIL <span class="ot">&lt;-</span> <span class="fu">counties</span>(<span class="st">"IL"</span>, <span class="at">cb=</span>T, <span class="at">year=</span><span class="dv">2019</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>pumasdf <span class="ot">&lt;-</span> <span class="fu">fortify</span>(pumasIL, <span class="at">region =</span> <span class="st">'PUMACE10'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># </span><span class="al">NOTE</span><span class="co">: To load data, you must download both the extract's data and the DDI</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># and also set the working directory to the folder with these files (or change the path below).</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co">#ipumsr key = 59cba10d8a5da536fc06b59daf9dae6406ec4a929d7d7341739c9cf9</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co">#set_ipums_api_key("59cba10d8a5da536fc06b59daf9dae6406ec4a929d7d7341739c9cf9")</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># # create a new extract object</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># extract_definition &lt;- define_extract_usa(</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co">#     "This is an example extract to submit via API.",</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co">#     c("us2018a","us2019a"),</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="co">#     c("AGE", "SEX", "RACE", "STATEFIP")</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co"># )</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="co"># # submit the extract to IPUMS USA for processing</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="co"># submitted_extract &lt;- submit_extract(extract_definition)</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="co"># # access the extract number, stored in the return value of submit_extract</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="co"># submitted_extract$number</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>ddi <span class="ot">&lt;-</span> <span class="fu">read_ipums_ddi</span>(<span class="st">"usa_00010.xml"</span>) <span class="co"># 2021 5-Year ACS IPUMS download</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_ipums_micro</span>(ddi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Use of data from IPUMS USA is subject to conditions including that users should
cite the data appropriately. Use command `ipums_conditions()` for more details.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data had 621164 obs</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># data &lt;- data %&gt;% filter(INCTOT != 9999999 &amp; INCTOT&gt;1,</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co">#                         INCWAGE &lt; 999998 &amp; INCWAGE&gt;0)</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># data drops to 455,581 obs with INCTOT filters</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 313249 with INCWAGE filters</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>pums_weighted <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(PUMA, COUNTYFIP) <span class="sc">%&gt;%</span> </span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">weighted =</span> <span class="fu">sum</span>(PERWT)) <span class="sc">%&gt;%</span> </span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">PUMA =</span> <span class="fu">str_pad</span>(PUMA, <span class="dv">5</span>, <span class="at">pad=</span><span class="st">"0"</span>),</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">countyFIP =</span> <span class="fu">str_pad</span>(COUNTYFIP, <span class="dv">3</span>, <span class="at">pad =</span> <span class="st">"0"</span>))</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>pums_unweight <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(PUMA, COUNTYFIP) <span class="sc">%&gt;%</span> </span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">unweight =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="co">#unweighted</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">PUMA =</span> <span class="fu">str_pad</span>(PUMA, <span class="dv">5</span>, <span class="at">pad=</span><span class="st">"0"</span>),</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">countyFIP =</span> <span class="fu">str_pad</span>(COUNTYFIP, <span class="dv">3</span>, <span class="at">pad =</span> <span class="st">"0"</span>))</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>plotweighted <span class="ot">&lt;-</span> pumasdf <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(pums_weighted, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"PUMACE10"</span> <span class="ot">=</span> <span class="st">"PUMA"</span>))</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>plotunweight <span class="ot">&lt;-</span> pumasdf <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(pums_unweight, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"PUMACE10"</span> <span class="ot">=</span> <span class="st">"PUMA"</span>))</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plotweighted[<span class="st">"weighted"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plotunweight[<span class="st">"unweight"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>FIPweighted <span class="ot">&lt;-</span> countyIL <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(pums_weighted, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"COUNTYFP"</span> <span class="ot">=</span> <span class="st">"countyFIP"</span>))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>FIPunweight <span class="ot">&lt;-</span> countyIL <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(pums_unweight, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"COUNTYFP"</span> <span class="ot">=</span> <span class="st">"countyFIP"</span>))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(FIPweighted[<span class="st">"weighted"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_files/figure-html/unnamed-chunk-3-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(FIPunweight[<span class="st">"unweight"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_files/figure-html/unnamed-chunk-3-4.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>plotDF <span class="ot">&lt;-</span> pumasdf <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(pums_weighted, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"PUMACE10"</span> <span class="ot">=</span> <span class="st">"PUMA"</span>))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plotDF[<span class="st">"weighted"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_files/figure-html/unnamed-chunk-3-5.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(countyIL[<span class="st">"COUNTYFP"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_files/figure-html/unnamed-chunk-3-6.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="pumas-vs-commzone-vs-counties" class="level4">
<h4 class="anchored" data-anchor-id="pumas-vs-commzone-vs-counties">PUMAS vs COMMZONE vs COUNTIES</h4>
<p><a href="https://eig.org/the-uneven-geography-of-remote-work/">Link from Francis on COMZONE variable</a> (Commuter Zones)</p>
<p><a href="https://univofillinois.maps.arcgis.com/apps/mapviewer/index.html?layers=71eb4ef236ca42c4b577a0a105e790e2">Interactive ESRI Map of all PUMA outlines</a></p>
<p><a href="https://atcoordinates.info/2019/05/13/calculating-mean-income-for-groups-of-geographies-with-census-acs-data/">Article on calculating mean income for groups of geographies with ACS data</a></p>
<div class="cell">

</div>
</section>
<section id="occupation-codes" class="level3">
<h3 class="anchored" data-anchor-id="occupation-codes">Occupation codes</h3>
<p><code>OCC2010</code> is a harmonized occupation coding scheme as broad groups. These are 4 characters long and are the first 4 characters of the longer ONET &amp; SOC codes.</p>
<p><code>OCCSOC</code> is 6 digits long. It is the first 6 digits of 8-digit ONET code.</p>
<ul>
<li>Please note that in some cases the SOC occupation codes are aggregated if they do not have an exact match to a Census occupation code or to preserve confidentiality in cases where the category contained fewer than 10,000 people nationwide.</li>
</ul>
<p><code>LABFORCE</code> for if in labor force. 1 = not in labor force, 2 = in labor force, 0 is NA</p>
<p><code>EMPSTAT</code> and <code>EMPSTATD</code> for employment status (simple and the detailed version). 1=employed, 2=unemployed, 3=not in labor force for empstat, 0 is NA</p>
<p><code>CLASSWKRD</code> might be useful. Contains info on self-employed, wages, salary, etc for class of worker.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>For persons who are unemployed, the data refer to the most recent job if it was within the last 5 years.</p>
</div>
</div>
</section>
<section id="descriptive-stats" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-stats">Descriptive Stats</h3>
<p>IPUMS <a href="https://usa.ipums.org/usa/repwt.shtml">link for Survey package</a></p>
<p>IPUMS OCC codes over time <a href="https://usa.ipums.org/usa/volii/occsoc18.shtml">link</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>EMPSTAT) <span class="co"># unweighted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1      2      3 
108919 297316  17293 197636 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">as_factor</span>(EMPSTAT)) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">n=</span><span class="fu">sum</span>(PERWT)) <span class="sc">%&gt;%</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span> n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 x 3
  `as_factor(EMPSTAT)`       n    pct
  &lt;fct&gt;                  &lt;dbl&gt;  &lt;dbl&gt;
1 N/A                  2544419 0.198 
2 Employed             6279200 0.490 
3 Unemployed            413460 0.0322
4 Not in labor force   3584734 0.280 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(MULTYEAR <span class="sc">&gt;</span> <span class="dv">2019</span>) <span class="sc">%&gt;%</span> <span class="co"># post-COVID</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">as_factor</span>(EMPSTAT)) <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">n=</span><span class="fu">sum</span>(PERWT)) <span class="sc">%&gt;%</span> </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span> n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 x 3
  `as_factor(EMPSTAT)`       n    pct
  &lt;fct&gt;                  &lt;dbl&gt;  &lt;dbl&gt;
1 N/A                  1013523 0.197 
2 Employed             2474254 0.482 
3 Unemployed            194823 0.0379
4 Not in labor force   1455856 0.283 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(MULTYEAR <span class="sc">&lt;=</span> <span class="dv">2019</span>) <span class="sc">%&gt;%</span> <span class="co"># pre-COVID</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">as_factor</span>(EMPSTAT)) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">n=</span><span class="fu">sum</span>(PERWT)) <span class="sc">%&gt;%</span> </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span> n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 x 3
  `as_factor(EMPSTAT)`       n    pct
  &lt;fct&gt;                  &lt;dbl&gt;  &lt;dbl&gt;
1 N/A                  1530896 0.199 
2 Employed             3804946 0.495 
3 Unemployed            218637 0.0285
4 Not in labor force   2128878 0.277 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>LABFORCE) <span class="co"># unweighted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1      2 
108919 197636 314609 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(<span class="fu">as_factor</span>(LABFORCE)) <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">n=</span><span class="fu">sum</span>(PERWT)) <span class="sc">%&gt;%</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span> n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 x 3
  `as_factor(LABFORCE)`            n   pct
  &lt;fct&gt;                        &lt;dbl&gt; &lt;dbl&gt;
1 N/A                        2544419 0.198
2 No, not in the labor force 3584734 0.280
3 Yes, in the labor force    6692660 0.522</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>CLASSWKR)<span class="co"># unweighted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1      2 
249658  33932 337574 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">as_factor</span>(CLASSWKR)) <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">n=</span><span class="fu">sum</span>(PERWT)) <span class="sc">%&gt;%</span> </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span> n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 x 3
  `as_factor(CLASSWKR)`       n    pct
  &lt;fct&gt;                   &lt;dbl&gt;  &lt;dbl&gt;
1 N/A                   5163029 0.403 
2 Self-employed          661164 0.0516
3 Works for wages       6997620 0.546 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(MULTYEAR) <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 x 2
# Groups:   MULTYEAR [5]
  MULTYEAR      n
     &lt;dbl&gt;  &lt;int&gt;
1     2017 126482
2     2018 126456
3     2019 125007
4     2020 116596
5     2021 126623</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(MULTYEAR,TRANWORK) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">sum</span>(PERWT)) <span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> MULTYEAR, <span class="at">values_from =</span> n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'MULTYEAR'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 x 6
                                     TRANWORK `2017` `2018` `2019` `2020` `2021`
                                    &lt;int+lbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1  0 [N/A]                                   1.34e6 1.31e6 1.29e6 1.38e6 1.35e6
 2 10 [Auto, truck, or van]                   1.00e6 1.01e6 9.96e5 8.88e5 8.74e5
 3 20 [Motorcycle]                            9.29e2 8.46e2 6.44e2 4.65e2 7.65e2
 4 31 [Bus]                                   4.62e4 4.40e4 4.48e4 2.92e4 2.28e4
 5 34 [Light rail, streetcar, or trolley (Ca~ 1.05e3 5.14e2 1.70e3 1.15e3 5.16e2
 6 36 [Subway or elevated]                    4.40e4 4.31e4 4.27e4 2.47e4 1.56e4
 7 37 [Long-distance train or commuter train] 2.95e4 3.12e4 3.02e4 1.59e4 8.19e3
 8 38 [Taxicab]                               4.12e3 3.70e3 5.15e3 3.08e3 3.10e3
 9 39 [Ferryboat]                             8.5 e1 1.96e2 1.66e2 2.5 e1 1.69e2
10 50 [Bicycle]                               8.24e3 7.53e3 6.96e3 5.05e3 6.55e3
11 60 [Walked only]                           3.61e4 3.45e4 3.84e4 2.86e4 3.16e4
12 70 [Other]                                 1.03e4 1.02e4 1.00e4 1.09e4 1.29e4
13 80 [Worked at home]                        6.22e4 6.40e4 6.65e4 1.99e5 2.32e5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("pollster")</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(<span class="at">df =</span> data, <span class="at">variable =</span> LABFORCE, <span class="at">weight =</span> PERWT )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 x 5
  Response                   Frequency Percent `Valid Percent` `Cumulative Per~`
  &lt;fct&gt;                          &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt;             &lt;dbl&gt;
1 N/A                          2544419    19.8            19.8              19.8
2 No, not in the labor force   3584734    28.0            28.0              47.8
3 Yes, in the labor force      6692660    52.2            52.2             100  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">crosstab</span>(data, <span class="at">x=</span>MULTYEAR, <span class="at">y =</span> LABFORCE, <span class="at">weight =</span> PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 x 5
  MULTYEAR `N/A` `No, not in the labor force` `Yes, in the labor force`       n
     &lt;dbl&gt; &lt;dbl&gt;                        &lt;dbl&gt;                     &lt;dbl&gt;   &lt;dbl&gt;
1     2017  20.2                         27.6                      52.2 2586594
2     2018  19.8                         27.7                      52.5 2563378
3     2019  19.7                         27.9                      52.4 2533385
4     2020  19.8                         28.3                      51.9 2582031
5     2021  19.6                         28.3                      52.0 2556425</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(data, EMPSTAT, PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 x 5
  Response           Frequency Percent `Valid Percent` `Cumulative Percent`
  &lt;fct&gt;                  &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt;                &lt;dbl&gt;
1 N/A                  2544419   19.8            19.8                  19.8
2 Employed             6279200   49.0            49.0                  68.8
3 Unemployed            413460    3.22            3.22                 72.0
4 Not in labor force   3584734   28.0            28.0                 100  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">crosstab</span>(data, <span class="at">x=</span>MULTYEAR, <span class="at">y =</span> EMPSTAT, <span class="at">weight =</span> PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 x 6
  MULTYEAR `N/A` Employed Unemployed `Not in labor force`       n
     &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;                &lt;dbl&gt;   &lt;dbl&gt;
1     2017  20.2     49.0       3.19                 27.6 2586594
2     2018  19.8     49.6       2.87                 27.7 2563378
3     2019  19.7     49.9       2.47                 27.9 2533385
4     2020  19.8     48.1       3.80                 28.3 2582031
5     2021  19.6     48.2       3.79                 28.3 2556425</code></pre>
</div>
</div>
<p><del>Unweighted - EMPSTAT: 297,000 observations are employed, 17,000 unemployed observations, and 198,000 observations are not in the workforce (109,000 NAs)</del></p>
<p><del>LABFORCE: 315,000 are in labor force, 197,000 are not. (109,000 NAs)</del></p>
<p><del>CLASSWKR: Of these, 338,000 work for wages and 34,000 people are self-employed. (250,000 NA)</del></p>
<p><u>Weighted</u> -</p>
<p>LABFORCE: 6,692,660 people (52%) are in the labor force. 3,584,734 (28%) of people are not in the labor force. 2,544,419 (20%) of observations missing values.</p>
<p>EMPSTAT: 6,279,200 people are employed (49%), 413,460 people are unemployed(3.2%), and 3,584,734 are not in the labor force (30%). There are 2,544,419 missing values; Same as LABFORCE.</p>
<ul>
<li>employed and unemployed equal number of people in labor force - that’s good</li>
</ul>
<p>CLASSWKR: 6,997,620 people (55%) work for wages. 661,164 (5%) are self employed.</p>
<p><strong>Pre and Post COVID values</strong>: when aggregating values before and after 2019, there is a slight difference in the percent of the population that is unemployed (which is expected since there was a pandemic)</p>
<p>So far so good. Makes sense.</p>
<p>Location of primary workplace: 5,936,960 people worked in Illinois</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># State worked in:</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co">#0=NA, 17=Illinois</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="co"># ipums_var_desc(data, PWSTATE2)</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">PWSTATE2_clean =</span> <span class="fu">as_factor</span>(<span class="fu">lbl_na_if</span>(PWSTATE2, <span class="sc">~</span>.val <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>))))</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(PWSTATE2) <span class="sc">%&gt;%</span></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">n=</span><span class="fu">sum</span>(PERWT)) <span class="sc">%&gt;%</span> <span class="co">#number of people that match that observation</span></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span> n<span class="sc">/</span><span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span> </span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pct))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 59 x 3
          PWSTATE2       n      pct
         &lt;int+lbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
 1  0 [N/A]        6673403 0.520   
 2 17 [Illinois]   5936960 0.463   
 3 29 [Missouri]     82454 0.00643 
 4 18 [Indiana]      34228 0.00267 
 5 19 [Iowa]         33713 0.00263 
 6 55 [Wisconsin]    30743 0.00240 
 7 21 [Kentucky]      4744 0.000370
 8 26 [Michigan]      2779 0.000217
 9  6 [California]    2210 0.000172
10 48 [Texas]         1967 0.000153
# ... with 49 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># postCOVID primary location of workplace</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(MULTYEAR <span class="sc">&gt;</span> <span class="dv">2019</span>) <span class="sc">%&gt;%</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">as_factor</span>(PWSTATE2_clean)) <span class="sc">%&gt;%</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a> dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">n=</span><span class="fu">sum</span>(PERWT)) <span class="sc">%&gt;%</span> </span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span> <span class="fu">round</span>(n<span class="sc">/</span><span class="fu">sum</span>(n), <span class="at">digits =</span> <span class="dv">2</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pct))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 52 x 3
   `as_factor(PWSTATE2_clean)`       n   pct
   &lt;fct&gt;                         &lt;dbl&gt; &lt;dbl&gt;
 1 &lt;NA&gt;                        2725195  0.53
 2 Illinois                    2337304  0.45
 3 Missouri                      28211  0.01
 4 Alabama                          38  0   
 5 Alaska                           15  0   
 6 Arizona                         341  0   
 7 Arkansas                         43  0   
 8 California                      516  0   
 9 Colorado                         99  0   
10 Delaware                          1  0   
# ... with 42 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># preCOVID primary location of workplace </span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span> (MULTYEAR<span class="sc">&lt;=</span><span class="dv">2019</span>) <span class="sc">%&gt;%</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">as_factor</span>(PWSTATE2)) <span class="sc">%&gt;%</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">n=</span><span class="fu">sum</span>(PERWT)) <span class="sc">%&gt;%</span> </span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span> <span class="fu">round</span>(n<span class="sc">/</span><span class="fu">sum</span>(n), <span class="at">digits =</span> <span class="dv">2</span> ) ) <span class="sc">%&gt;%</span> </span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pct))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 56 x 3
   `as_factor(PWSTATE2)`       n   pct
   &lt;fct&gt;                   &lt;dbl&gt; &lt;dbl&gt;
 1 N/A                   3948208  0.51
 2 Illinois              3599656  0.47
 3 Missouri                54243  0.01
 4 Alabama                   201  0   
 5 Arizona                   344  0   
 6 Arkansas                  160  0   
 7 California               1694  0   
 8 Colorado                  221  0   
 9 Connecticut               171  0   
10 Delaware                   49  0   
# ... with 46 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCTOT))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -10174   12600   40000 1672007  103580 9999999 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCWAGE))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      0       0   28000  204900   98186  999999 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(data<span class="sc">$</span>INCTOT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$labels
                                   $9,900 (1980) 
                                           -9995 
                                 Net loss (1950) 
                                              -1 
                                            None 
                                               0 
1 or break even (2000, 2005-onward ACS and PRCS) 
                                               1 
                                             N/A 
                                         9999999 

$class
[1] "haven_labelled" "vctrs_vctr"     "double"        

$label
[1] "Total personal income"

$var_desc
[1] "INCTOT reports each respondent's total pre-tax personal income or losses from all sources for the previous year. The censuses collected information on income received from these sources during the previous calendar year; for the ACS and the PRCS, the reference period was the past 12 months. Amounts are expressed in contemporary dollars, and users studying change over time must adjust for inflation:\n\nUsers studying change over time must adjust for inflation. Consumer Price Index adjustment factors for the appropriate years can be found in the CPI99 variable.\n\nThe exception is the ACS/PRCS multi-year files, where all dollar amounts have been standardized to dollars as valued in the final year of data included in the file (e.g., 2007 dollars for the 2005-2007 3-year file). Additionally, more detail may be available than exists in the original ACS samples.\n\nUser Note: ACS respondents are surveyed throughout the year, and amounts do not reflect calendar year dollars. While the Census Bureau provides an adjustment factor (available in ADJUST), this is an imperfect solution. See the ACS income variables note for further details.\n\nFor a more complete discussion of the use of these factors to adjust for inflation, users may wish to see the IPUMS-CPS note on adjusting dollar amount variables for inflation."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(data<span class="sc">$</span>INCWAGE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$labels
Missing     N/A 
 999998  999999 

$class
[1] "haven_labelled" "vctrs_vctr"     "double"        

$label
[1] "Wage and salary income"

$var_desc
[1] "INCWAGE reports each respondent's total pre-tax wage and salary income - that is, money received as an employee - for the previous year. The censuses collected information on income received from these sources during the previous calendar year; for the ACS and the PRCS, the reference period was the past 12 months. Sources of income in INCWAGE include wages, salaries, commissions, cash bonuses, tips, and other money income received from an employer. Payments-in-kind or reimbursements for business expenses are not included. See the comparability discussion below for further information.\n\nAmounts are expressed in contemporary dollars, and users studying change over time must adjust for inflation (See INCTOT for Consumer Price Index adjustment factors). The exception is the ACS/PRCS multi-year files, where all dollar amounts have been standardized to dollars as valued in the final year of data included in the file (e.g., 2007 dollars for the 2005-2007 3-year file). Additionally, more detail may be available than exists in the original ACS samples.\n\nUser Note: ACS respondents are surveyed throughout the year, and amounts do not reflect calendar year dollars. While the Census Bureau provides an adjustment factor (available in ADJUST), this is an imperfect solution. See the ACS income variables note for further details."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">#data %&gt;% filter(INCTOT != 9999999  &amp; OCCSOC &gt;0 &amp; INCTOT&gt;1)</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="do">## 357,376 when adding OCCSOC filter greater than zero</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 999999 is missing values and want positive income values</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(INCTOT <span class="sc">!=</span> <span class="dv">9999999</span> <span class="sc">&amp;</span> INCTOT<span class="sc">&gt;</span><span class="dv">0</span>)  <span class="sc">%&gt;%</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 455,581 obs remaining</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(INCWAGE <span class="sc">!=</span> <span class="dv">999998</span> <span class="sc">&amp;</span> INCWAGE <span class="sc">!=</span> <span class="dv">999999</span> <span class="sc">&amp;</span> INCWAGE<span class="sc">&gt;</span><span class="dv">0</span>)</span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a><span class="co"># ~313000 obs remaining after both steps</span></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCTOT))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      1   22105   45000   64331   78502 1303718 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCWAGE))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      4   18758   41868   58603   73369  603943 </code></pre>
</div>
</div>
<p>Quartiles for both INCTOT and INCWAGE. Boxplots to visualize data distribution are below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>INCTOT)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Don't know how to automatically pick scale for object of type haven_labelled/vctrs_vctr/double. Defaulting to continuous.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="WorkFromHome_files/figure-html/inctot-calcs2-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># outliers mostly after $400,000</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>INCWAGE)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Don't know how to automatically pick scale for object of type haven_labelled/vctrs_vctr/double. Defaulting to continuous.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="WorkFromHome_files/figure-html/inctot-calcs2-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a> <span class="co"># filter(INCTOT &lt;450000) %&gt;%</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">inctot_decile =</span> <span class="fu">ntile</span>(INCTOT, <span class="dv">10</span>),</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">incwage_decile =</span> <span class="fu">ntile</span>(INCWAGE, <span class="dv">10</span>)) <span class="co">#</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>inctot_decile) <span class="co">#equal number of people, yay</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2     3     4     5     6     7     8     9    10 
31326 31326 31325 31325 31325 31325 31325 31325 31325 31325 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># histogram of total income</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>INCTOT, <span class="at">bins =</span> <span class="dv">30</span>) <span class="co"># unweighted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(xlim, ylim, "", ...): "bins" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(main = main, sub = sub, xlab = xlab, ylab = ylab, ...): "bins"
is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(1, ...): "bins" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(2, ...): "bins" is not a graphical parameter</code></pre>
</div>
<div class="cell-output-display">
<p><img src="WorkFromHome_files/figure-html/inctot-calcs2-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>INCTOT)) <span class="sc">+</span> </span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span>  <span class="dv">30</span>) <span class="sc">+</span> </span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> <span class="fu">label_dollar</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_files/figure-html/inctot-calcs2-4.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(data, INCTOT, <span class="at">weight =</span> PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18,422 x 5
   Response                   Frequency Percent `Valid Percent` `Cumulative Pe~`
   &lt;fct&gt;                          &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt;            &lt;dbl&gt;
 1 1 or break even (2000, 20~        87 1.32e-3        0.00132           0.00132
 2 4                                 65 9.86e-4        0.000986          0.00231
 3 10                               235 3.57e-3        0.00357           0.00587
 4 20                               172 2.61e-3        0.00261           0.00848
 5 21                               210 3.19e-3        0.00319           0.0117 
 6 22                                41 6.22e-4        0.000622          0.0123 
 7 30                               234 3.55e-3        0.00355           0.0158 
 8 32                               123 1.87e-3        0.00187           0.0177 
 9 33                                96 1.46e-3        0.00146           0.0192 
10 40                                42 6.37e-4        0.000637          0.0198 
# ... with 18,412 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(data, inctot_decile, <span class="at">weight =</span> PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 x 5
   Response Frequency Percent `Valid Percent` `Cumulative Percent`
   &lt;fct&gt;        &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt;                &lt;dbl&gt;
 1 1           632477    9.60            9.60                 9.60
 2 2           684194   10.4            10.4                 20.0 
 3 3           702960   10.7            10.7                 30.6 
 4 4           692138   10.5            10.5                 41.1 
 5 5           665747   10.1            10.1                 51.2 
 6 6           644519    9.78            9.78                61.0 
 7 7           644244    9.78            9.78                70.8 
 8 8           645557    9.80            9.80                80.6 
 9 9           647888    9.83            9.83                90.4 
10 10          630628    9.57            9.57               100   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wtd.hist</span>(data<span class="sc">$</span>INCTOT, <span class="at">weight =</span> data<span class="sc">$</span>PERWT, <span class="at">breaks =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_files/figure-html/inctot-calcs2-5.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>         <span class="co">#breaks = c(0.1, 0.2, 0.3, .4, .5, .6,.7,.8,.9,1))</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="co">#sum(data$PERWT)</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>data_decile <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a><span class="co">#  filter(INCTOT &lt; 400000) %&gt;%</span></span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a><span class="co">#  dplyr::group_by(ntile(INCTOT, 10) ) %&gt;%</span></span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">decile =</span> <span class="fu">ntile</span>(INCTOT, <span class="dv">10</span>) ) </span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data_decile<span class="sc">$</span>decile) <span class="co">#yay equal numbers of people in each decile group</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2     3     4     5     6     7     8     9    10 
31326 31326 31325 31325 31325 31325 31325 31325 31325 31325 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCTOT))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      1   22105   45000   64331   78502 1303718 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCEARN))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  -7880   18900   41868   59642   74183 1000263 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(data<span class="sc">$</span>INCTOT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$labels
                                   $9,900 (1980) 
                                           -9995 
                                 Net loss (1950) 
                                              -1 
                                            None 
                                               0 
1 or break even (2000, 2005-onward ACS and PRCS) 
                                               1 
                                             N/A 
                                         9999999 

$label
[1] "Total personal income"

$var_desc
[1] "INCTOT reports each respondent's total pre-tax personal income or losses from all sources for the previous year. The censuses collected information on income received from these sources during the previous calendar year; for the ACS and the PRCS, the reference period was the past 12 months. Amounts are expressed in contemporary dollars, and users studying change over time must adjust for inflation:\n\nUsers studying change over time must adjust for inflation. Consumer Price Index adjustment factors for the appropriate years can be found in the CPI99 variable.\n\nThe exception is the ACS/PRCS multi-year files, where all dollar amounts have been standardized to dollars as valued in the final year of data included in the file (e.g., 2007 dollars for the 2005-2007 3-year file). Additionally, more detail may be available than exists in the original ACS samples.\n\nUser Note: ACS respondents are surveyed throughout the year, and amounts do not reflect calendar year dollars. While the Census Bureau provides an adjustment factor (available in ADJUST), this is an imperfect solution. See the ACS income variables note for further details.\n\nFor a more complete discussion of the use of these factors to adjust for inflation, users may wish to see the IPUMS-CPS note on adjusting dollar amount variables for inflation."

$class
[1] "haven_labelled" "vctrs_vctr"     "double"        </code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(data<span class="sc">$</span>INCEARN)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$labels
                                   No earnings 
                                             0 
1 or break even (2000, 2005-2007 ACS and PRCS) 
                                             1 

$label
[1] "Total personal earned income"

$var_desc
[1] "INCEARN reports income earned from wages or a person's own business or farm for the previous year. The censuses collected information on income received from these sources during the previous calendar year; for the ACS and the PRCS, the reference period was the past 12 months. The value of INCEARN is the total for the IPUMS variables INCWAGE, INCBUS, and INCFARM (for 1990) and for INCWAGE and INCBUS00 (for the 2000 census, the ACS, and the PRCS). Note that these components of INCEARN are themselves already Top coded. See those variables for further discussion.  Because the universe for those variables is age 16+, all persons under age 16 have a value of 0 for INCEARN.\n\nAmounts are expressed in contemporary dollars, and users studying change over time must adjust for inflation (See INCTOT for Consumer Price Index adjustment factors).  The exception is the ACS/PRCS multi-year files, where all dollar amounts have been standardized to dollars as valued in the final year of data included in the file (e.g., 2007 dollars for the 2005-2007 3-year file). Additionally, more detail may be available than exists in the original ACS samples.  \n\nUser Note: ACS respondents are surveyed throughout the year, and amounts do not reflect calendar year dollars. While the Census Bureau provides an adjustment factor (available in ADJUST), this is an imperfect solution. See the ACS income variables note for further details."

$class
[1] "haven_labelled" "vctrs_vctr"     "double"        </code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a> <span class="co"># filter(INCWAGE &lt;450000) %&gt;%</span></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">incearn_decile =</span> <span class="fu">ntile</span>(INCEARN, <span class="dv">10</span>)) <span class="co">#adds a variable to indicate which decile an observation falls within</span></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>breaksummary <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(incearn_decile) <span class="sc">%&gt;%</span></span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">decile_min =</span> <span class="fu">min</span>(INCEARN),</span>
<span id="cb87-8"><a href="#cb87-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">decile_max =</span> <span class="fu">max</span>(INCEARN)</span>
<span id="cb87-9"><a href="#cb87-9" aria-hidden="true" tabindex="-1"></a>            ) </span>
<span id="cb87-10"><a href="#cb87-10" aria-hidden="true" tabindex="-1"></a>breaksummary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 x 3
   incearn_decile decile_min decile_max
            &lt;int&gt;  &lt;dbl+lbl&gt;  &lt;dbl+lbl&gt;
 1              1      -7880       5395
 2              2       5395      13777
 3              3      13777      23237
 4              4      23237      32369
 5              5      32369      41868
 6              6      41868      52882
 7              7      52882      65705
 8              8      65705      84781
 9              9      84781     118686
10             10     118686    1000263</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>incearn_decile) <span class="co">#equal number of people, yay</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2     3     4     5     6     7     8     9    10 
31326 31326 31325 31325 31325 31325 31325 31325 31325 31325 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co"># histogram of wages and salary income</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a> <span class="co"># unweighted</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>INCEARN)) <span class="sc">+</span> </span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_bin</span>(<span class="at">bins=</span><span class="dv">30</span>)<span class="sc">+</span> </span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> <span class="fu">label_dollar</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_files/figure-html/incearn-descripstats-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(data, INCEARN, <span class="at">weight =</span> PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5,965 x 5
   Response Frequency   Percent `Valid Percent` `Cumulative Percent`
   &lt;fct&gt;        &lt;dbl&gt;     &lt;dbl&gt;           &lt;dbl&gt;                &lt;dbl&gt;
 1 -7880           22 0.000334        0.000334              0.000334
 2 -7065            4 0.0000607       0.0000607             0.000395
 3 -6582           24 0.000364        0.000364              0.000759
 4 -6465           27 0.000410        0.000410              0.00117 
 5 -6042           25 0.000379        0.000379              0.00155 
 6 -5935           17 0.000258        0.000258              0.00181 
 7 -5718           18 0.000273        0.000273              0.00208 
 8 -5338           11 0.000167        0.000167              0.00225 
 9 -5305           25 0.000379        0.000379              0.00263 
10 -5000           12 0.000182        0.000182              0.00281 
# ... with 5,955 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(data, incearn_decile, <span class="at">weight =</span> PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 x 5
   Response Frequency Percent `Valid Percent` `Cumulative Percent`
   &lt;fct&gt;        &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt;                &lt;dbl&gt;
 1 1           604414    9.17            9.17                 9.17
 2 2           654927    9.94            9.94                19.1 
 3 3           690966   10.5            10.5                 29.6 
 4 4           703413   10.7            10.7                 40.3 
 5 5           679638   10.3            10.3                 50.6 
 6 6           656949    9.97            9.97                60.5 
 7 7           651537    9.89            9.89                70.4 
 8 8           653463    9.92            9.92                80.3 
 9 9           654301    9.93            9.93                90.3 
10 10          640744    9.72            9.72               100   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co">#unweighted</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wtd.hist</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCEARN), <span class="at">breaks =</span> <span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_files/figure-html/incearn-descripstats-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co">#weighted</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wtd.hist</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCEARN), <span class="at">breaks =</span> <span class="dv">30</span>,</span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">weight =</span> data<span class="sc">$</span>PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_files/figure-html/incearn-descripstats-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="observations-without-occ-codes" class="level4">
<h4 class="anchored" data-anchor-id="observations-without-occ-codes">Observations without OCC codes</h4>
<p>Look at the subset of data called <code>noOCCSOC</code>. Why do they not have OCC codes? Check work.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># noOCCSOC&lt;- data %&gt;% </span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   filter(OCCSOC == 0) #98205 with occsoc=0</span></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a><span class="co"># table(noOCCSOC$EMPSTAT)</span></span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a><span class="co"># before filtering out the incwage and inctot variables for 0's and negatives, </span></span>
<span id="cb98-7"><a href="#cb98-7" aria-hidden="true" tabindex="-1"></a><span class="co"># #98% of the people without Occupation codes are not in the labor force. Makes sense</span></span>
<span id="cb98-8"><a href="#cb98-8" aria-hidden="true" tabindex="-1"></a><span class="co"># all observations have occsoc codes after filtering for INCWAGE and INCTOT and previous steps</span></span>
<span id="cb98-9"><a href="#cb98-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-10"><a href="#cb98-10" aria-hidden="true" tabindex="-1"></a>data2 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(OCCSOC <span class="sc">!=</span> <span class="dv">0</span>) </span>
<span id="cb98-11"><a href="#cb98-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-12"><a href="#cb98-12" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(<span class="at">df =</span> data2, <span class="at">variable =</span> EMPSTAT, <span class="at">weight =</span> PERWT )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 x 5
  Response           Frequency Percent `Valid Percent` `Cumulative Percent`
  &lt;fct&gt;                  &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt;                &lt;dbl&gt;
1 Employed             6022515   91.4            91.4                  91.4
2 Unemployed            213366    3.24            3.24                 94.6
3 Not in labor force    354471    5.38            5.38                100  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">crosstab</span>(data2, <span class="at">x=</span>MULTYEAR, <span class="at">y =</span> LABFORCE, <span class="at">weight =</span> PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 x 4
  MULTYEAR `No, not in the labor force` `Yes, in the labor force`       n
     &lt;dbl&gt;                        &lt;dbl&gt;                     &lt;dbl&gt;   &lt;dbl&gt;
1     2017                         5.39                      94.6 1324650
2     2018                         5.37                      94.6 1328479
3     2019                         5.02                      95.0 1316192
4     2020                         6.00                      94.0 1331331
5     2021                         5.09                      94.9 1289700</code></pre>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(data2<span class="sc">$</span>PERWT) <span class="co"># 6.5 million people</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6590352</code></pre>
</div>
</div>
<p>Look at decile breaks for INCWAGE:</p>
<p><em>These are different than Xiaoyans</em>? Double check??</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>income_deciles <span class="ot">&lt;-</span> data2 <span class="sc">%&gt;%</span> </span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">ntile</span>(INCWAGE, <span class="dv">10</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">mean_inc =</span> <span class="fu">mean</span>(INCWAGE)) </span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a>income_deciles</span>
<span id="cb104-6"><a href="#cb104-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-7"><a href="#cb104-7" aria-hidden="true" tabindex="-1"></a>data2 <span class="sc">%&gt;%</span> </span>
<span id="cb104-8"><a href="#cb104-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">ntile</span>(INCWAGE,<span class="dv">10</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb104-9"><a href="#cb104-9" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">mean_inc =</span> <span class="fu">mean</span>(<span class="fu">as.numeric</span>(INCWAGE)) )<span class="sc">%&gt;%</span></span>
<span id="cb104-10"><a href="#cb104-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb104-11"><a href="#cb104-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">INCWAGE_decile=</span><span class="st">'ntile(INCWAGE,10)'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb104-12"><a href="#cb104-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">ntile</span>(INCWAGE_decile,<span class="dv">10</span>), <span class="at">y=</span>mean_inc)) <span class="sc">+</span> </span>
<span id="cb104-13"><a href="#cb104-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb104-14"><a href="#cb104-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Income decile"</span>, <span class="at">y=</span><span class="st">"Mean Income"</span>, <span class="at">title =</span> <span class="st">"Average Income for each Income Decile."</span>) <span class="sc">+</span></span>
<span id="cb104-15"><a href="#cb104-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>teleworkable2010.csv has the 6digit OCCSOC codes. I also added the 5 digit broader version that ends with a 0 in the 6th digit to increase the chances of matching.</p>
<p>Updated teleworkable2010.csv again with 4digitXX codes and 5digitXcodes to increase matching.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co">#telework csv uses data from Dingle and Nieman</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="co"># https://github.com/jdingel/DingelNeiman-workathome/blob/master/occ_manual_scores/input/Teleworkable_BNJDopinion.csv</span></span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a>telework<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"teleworkable2010.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: One or more parsing issues, see `problems()` for details</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 2535 Columns: 8
-- Column specification --------------------------------------------------------
Delimiter: ","
chr (4): onetsoccode, title, onetsoc_6digits, major_code_label
dbl (4): teleworkable, onetsoc_5digits2, onetsoccode_6figscombined, major_co...

i Use `spec()` to retrieve the full column specification for this data.
i Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>telework<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"teleworkable2018onwards.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1883 Columns: 4
-- Column specification --------------------------------------------------------
Delimiter: ","
chr (2): onetsoc_6digits, occ_label for 6 figs
dbl (2): Count_onetsoc_6digits, Average_teleworkable

i Use `spec()` to retrieve the full column specification for this data.
i Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="co"># causes problems for any occupation code that has XX in it!! </span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>data2<span class="sc">$</span>OCCSOC_num <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(data2<span class="sc">$</span>OCCSOC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: NAs introduced by coercion</code></pre>
</div>
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a>innerjoined<span class="ot">&lt;-</span><span class="fu">inner_join</span>(data2, telework, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"OCCSOC"</span><span class="ot">=</span> <span class="st">"onetsoc_6digits"</span>))</span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 285430 obs in innerjoin</span></span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 352729 obs after updating teleworkable2010 file with broader 5digit codes that 6digit 0</span></span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(innerjoined<span class="sc">$</span>Average_teleworkable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
    0.0     0.0     0.0     0.4     1.0     1.0   33114 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 306894 obs after adding 5digitsX and 4digitsXX codes to teleworkable.</span></span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a><span class="co"># teleworkable values are an average of occupations with same first 5 digits and first 4 digits. </span></span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a>leftjoined<span class="ot">&lt;-</span><span class="fu">left_join</span>(data2, telework, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"OCCSOC"</span><span class="ot">=</span> <span class="st">"onetsoc_6digits"</span>))</span>
<span id="cb114-5"><a href="#cb114-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-6"><a href="#cb114-6" aria-hidden="true" tabindex="-1"></a><span class="co">#innerjoined&lt;-inner_join(data2, telework, by = c("OCCSOC_num"= "BroadGroupCode"))</span></span>
<span id="cb114-7"><a href="#cb114-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-8"><a href="#cb114-8" aria-hidden="true" tabindex="-1"></a><span class="co">#leftjoined&lt;-left_join(data2, telework, by = c("OCCSOC_num"= "BroadGroupCode"))</span></span>
<span id="cb114-9"><a href="#cb114-9" aria-hidden="true" tabindex="-1"></a><span class="co"># keeps all observations in data 2 even if they don't match</span></span>
<span id="cb114-10"><a href="#cb114-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-11"><a href="#cb114-11" aria-hidden="true" tabindex="-1"></a><span class="co">#antijoin &lt;-anti_join(data2, telework, by = c("OCCSOC_num"= "onetsoc_6digits"))</span></span>
<span id="cb114-12"><a href="#cb114-12" aria-hidden="true" tabindex="-1"></a><span class="co"># 158525. Many were aggregated to 5digits with 6digit as 0.</span></span>
<span id="cb114-13"><a href="#cb114-13" aria-hidden="true" tabindex="-1"></a><span class="co"># 91403 obs after updating teleworkable file to 5digits with 6digit as 0</span></span>
<span id="cb114-14"><a href="#cb114-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-15"><a href="#cb114-15" aria-hidden="true" tabindex="-1"></a><span class="co">#couldnt use _num version due to XX in values.</span></span>
<span id="cb114-16"><a href="#cb114-16" aria-hidden="true" tabindex="-1"></a>antijoin <span class="ot">&lt;-</span><span class="fu">anti_join</span>(data2, telework, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"OCCSOC"</span><span class="ot">=</span> <span class="st">"onetsoc_6digits"</span>))</span>
<span id="cb114-17"><a href="#cb114-17" aria-hidden="true" tabindex="-1"></a><span class="co"># 50,659 obs after adding 5digitsX and 4digitsXX and 5digits with sixth as 0 to csv file</span></span>
<span id="cb114-18"><a href="#cb114-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-19"><a href="#cb114-19" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(antijoin<span class="sc">$</span>OCCSOC) <span class="co">#121 unique codes did not match.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>character(0)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="co"># down to 67 after adding 5digitsX and 4digitsXX and 5digits with sixth as 0 to csv file</span></span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a><span class="co">#joined &lt;- joined %&gt;% mutate(occsoc5digits = substr(OCCSOC,1,5))</span></span>
<span id="cb116-4"><a href="#cb116-4" aria-hidden="true" tabindex="-1"></a><span class="co">#table(joined$occsoc5digits)</span></span>
<span id="cb116-5"><a href="#cb116-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb116-6"><a href="#cb116-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb116-7"><a href="#cb116-7" aria-hidden="true" tabindex="-1"></a><span class="co">#table(joined$Teleworkable)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Drops a lot of observations using inner join (equivalent to Stata merge==1) this join. 67,299 observations match SOC codes. I think so many do not match due to the use of 2010 , 2019 transition, and 2018 SOC OCC codes. To check this, I try joining the ACS data with the updated 2018 codes. (Authors used 2010 codes in original paper but they did do one for states that appear to have the 2018 codes?) Double check this.</p>
<ul>
<li>Using the 2021 ACS 1-year Sample should use only 2018 OCC codes since that data should be collected after they transitioned their occupation codes.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>occ_2018 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"2018OCCcodes.csv"</span>)<span class="sc">%&gt;%</span> </span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">soc2018_6figs =</span> <span class="fu">as.character</span>(soc2018_6figs))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1016 Columns: 11
-- Column specification --------------------------------------------------------
Delimiter: ","
chr (5): O*NET-SOC 2019 Code, O*NET-SOC 2019 Title, 2018 SOC Code, 2018 SOC ...
dbl (5): SOC2018_2characters, ONETSOC2019_2characters, onet2019_6figs_nodec,...
lgl (1): teleworkable

i Use `spec()` to retrieve the full column specification for this data.
i Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a>joined2018codes <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(data2, occ_2018, </span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"OCCSOC"</span> <span class="ot">=</span> <span class="st">"soc2018_6figs"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">occsoc5digits =</span> <span class="fu">substr</span>(OCCSOC,<span class="dv">1</span>,<span class="dv">5</span>))</span>
<span id="cb119-4"><a href="#cb119-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-5"><a href="#cb119-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(joined2018codes<span class="sc">$</span>occsoc5digits)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
11102 11201 11202 11301 11302 11303 11305 11306 11307 11311 11312 11313 11901 
 2163   169  2606   593  1418  8733  4176   434  1220    40   769   135   866 
11902 11904 11905 11908 11911 11912 11914 11915 11916 13101 13102 13104 13105 
 1116   716  1575   157  1399   177   819   944    22    70  1029  4144   279 
13108 13111 13112 13113 13114 13115 13116 13119 13201 13203 13204 13205 13206 
 2595  2368   344   231   153   330  1768  4185  4245    81    98  1844    45 
13208 15121 15122 15124 15125 15129 15201 15203 17101 17201 17204 17205 17206 
  365  3059    42   839  4109 15480   142   258   509    86   132  2190    81 
17208 17212 17213 17214 17301 17302 17303 19202 19204 19209 19301 19303 19305 
   43     6    93  2337    90   185    98    19   148  1222    98   208    49 
19402 19403 21101 21102 21109 21201 21202 21209 23101 23201 23209 25304 25402 
   59   146  1545  1708   596  1278   169   164    50   842   212   482   558 
25403 27102 27201 27202 27204 27209 27301 27302 27303 27304 27309 27402 29101 
  130  1060  1125   875   318    56    64   140   277  1298   242   248   121 
29103 29104 29105 29107 29108 29112 29113 29114 29115 29118 29129 29203 29204 
  173   103   682   470    22  1909   182 35760    53    46   425   915   447 
29205 29206 29207 29208 31112 31113 31901 31909 33101 33102 33201 33301 33302 
 1302  1223   385   163  3278  2740   236  1879   322   105   664   881   636 
33901 33902 33909 35101 35202 35301 35302 35303 35304 35901 35902 35903 35909 
   23   189   321  1643  1958   866  2904  3701   446   670   701   691    37 
37101 37201 37202 37301 39201 39202 39303 39403 39501 39509 39901 39903 39904 
  564  1664   117  2049    78   509   130   106  1137   417  3882  1254   200 
39909 41101 41202 41203 41301 41302 41303 41304 41309 41903 41904 41909 43101 
  437  7592   369  6214   391  1060   667   142  1526   116    96   977  2487 
43201 43202 43209 43301 43302 43303 43305 43306 43307 43403 43404 43405 43406 
   62    52    16   225   955  2482   335   107   762   148    69  5796    65 
43407 43408 43411 43412 43413 43414 43416 43417 43418 43501 43502 43503 43504 
  334   205   328   336   249    23   119  2534   208   146   671   603    52 
43505 43506 43507 43511 43601 43902 43904 43905 43906 43907 43908 43911 45101 
 1193   723  1387   166  6658  1050   579   160  3023    89    25    43    55 
45201 45204 45303 45401 47101 47201 47203 47206 47211 47212 47215 47216 47218 
   22    83     5    50  1782    56  1839  2587  1592    48  2129    20   346 
47221 47222 47223 47401 47402 47403 47404 47405 47406 47503 49101 49201 49209 
  259   177    12   236    56    23    51   313    45    11   473   273   200 
49301 49302 49303 49902 49903 49904 49905 49907 49909 51101 51203 51204 51301 
  159  1738   666   671    71   225   389  1255   156  1907    32    72   381 
51309 51403 51404 51411 51511 51601 51602 51603 51609 51701 51702 51704 51802 
  640   302   819   190   567   313    55   209    35    60    20    44   366 
51803 51904 51905 51906 51907 51911 51915 51919 53203 53301 53305 53309 53403 
  196    61     6  1699   126   737    46   482   286    18  2281   244   168 
53602 53605 53606 53702 53705 53706 53708 
  127   228    73   132  1714 17528   207 </code></pre>
</div>
</div>
<p>joining the ACS data to the 2018 SOC OCC codes results in 322,863 matches. (322863/357380 = 0.9034165% matched)</p>
<p><strong>OCC2010 variable labels:</strong></p>
<p>From DDI on IPUMS download: https://live.usa.datadownload.ipums.org/web/extracts/usa/1985137/usa_00006.xml#OCC</p>
<p>Management, Business, Science, and Arts = 10-430<br>
Business Operations Specialists = 500-730<br>
Financial Specialists = 800-950<br>
Computer and Mathematical = 1000-1240<br>
Architecture and Engineering = 1300-1540<br>
Technicians = 1550-1560<br>
Life, Physical, and Social Science = 1600-1980<br>
Community and Social Services = 2000-2060<br>
Legal = 2100-2150<br>
Education, Training, and Library = 2200-2550<br>
Arts, Design, Entertainment, Sports, and Media = 2600-2920<br>
Healthcare Practitioners and Technicians = 3000-3540<br>
Healthcare Support = 3600-3650<br>
Protective Service = 3700-3950<br>
Food Preparation and Serving = 4000-4150<br>
Building and Grounds Cleaning and Maintenance = 4200-4250<br>
Personal Care and Service = 4300-4650<br>
Sales and Related = 4700-4965<br>
Office and Administrative Support = 5000-5940<br>
Farming, Fishing, and Forestry = 6005-6130<br>
Construction = 6200-6765<br>
Extraction = 6800-6940<br>
Installation, Maintenance, and Repair = 7000-7630<br>
Production = 7700-8965<br>
Transportation and Material Moving = 9000-9750<br>
Military Specific = 9800-9830<br>
Unemployed (no occupation for 5+ years) or Never Worked = 9920<br>
</p>
</section>
</section>
</section>
</section>
<section id="stuff-im-not-ready-to-delete-yet" class="level1">
<h1>Stuff I’m not ready to delete yet</h1>
<section id="chatgpt-attempt" class="level2">
<h2 class="anchored" data-anchor-id="chatgpt-attempt">ChatGPT attempt</h2>
<p>I attempted to ask Chat GPT how to pull and merge ACS and Onet data. Ignore this section.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ipumsr)</span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-3"><a href="#cb121-3" aria-hidden="true" tabindex="-1"></a>il_acs <span class="ot">&lt;-</span> <span class="fu">load_ipums_acs</span>(<span class="at">year =</span> <span class="dv">2021</span>, <span class="at">survey =</span> <span class="st">"5-year"</span>, <span class="at">statefip =</span> <span class="dv">17</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">c</span>(<span class="st">"AGE"</span>, <span class="st">"SEX"</span>, <span class="st">"RACE"</span>, <span class="st">"INCWAGE"</span>))</span>
<span id="cb121-4"><a href="#cb121-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-5"><a href="#cb121-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(il_acs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="summary-tables-of-households-in-il-state-2016-2020-acs" class="level3">
<h3 class="anchored" data-anchor-id="summary-tables-of-households-in-il-state-2016-2020-acs">Summary tables of Households in IL State, 2016-2020 ACS</h3>
<p>These examples all use summary tables (Similar to what Prof.&nbsp;Wu does in Stata code) except these use API commands instead of downloading CSVs from the IPUMS website.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidycensus)</span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(acs)</span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-4"><a href="#cb122-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-5"><a href="#cb122-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Download data for table B19001</span></span>
<span id="cb122-6"><a href="#cb122-6" aria-hidden="true" tabindex="-1"></a>b19001 <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(<span class="at">geography =</span> <span class="st">"state"</span>, <span class="at">table =</span> <span class="st">"B19001"</span>, <span class="at">year =</span> <span class="dv">2019</span>, <span class="at">state =</span> <span class="st">"IL"</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>moe) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">hh_pct =</span> estimate <span class="sc">/</span> <span class="dv">4846134</span> <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(variable <span class="sc">!=</span> <span class="st">"B19001_001"</span>)</span>
<span id="cb122-7"><a href="#cb122-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-8"><a href="#cb122-8" aria-hidden="true" tabindex="-1"></a><span class="co"># View the data</span></span>
<span id="cb122-9"><a href="#cb122-9" aria-hidden="true" tabindex="-1"></a>b19001</span>
<span id="cb122-10"><a href="#cb122-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-11"><a href="#cb122-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-12"><a href="#cb122-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-13"><a href="#cb122-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Add labels to the income levels</span></span>
<span id="cb122-14"><a href="#cb122-14" aria-hidden="true" tabindex="-1"></a>income_labels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Less than $10,000"</span>, <span class="st">"$10,000 to $14,999"</span>, <span class="st">"$15,000 $19,999"</span>, <span class="st">"$20,000 to $24,999"</span>, <span class="st">"$25,000 to $29,999"</span>, <span class="st">"$30,000 to $34,999"</span>, <span class="st">"$35,000 to $39,999"</span>, <span class="st">"$40,000 to $44,999"</span>, <span class="st">"$45,000 to $49,999"</span>, <span class="st">"$50,000 to $59,999"</span>, <span class="st">"$60,000 to $74,999"</span>, <span class="st">"$75,000 to $99,999"</span>, <span class="st">"$100,000 to $124,999"</span>, <span class="st">"$125,000 to $149,999"</span>, <span class="st">"$150,000 to $199,999"</span>, <span class="st">"$200,000 or More"</span>)</span>
<span id="cb122-15"><a href="#cb122-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-16"><a href="#cb122-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the data with labels</span></span>
<span id="cb122-17"><a href="#cb122-17" aria-hidden="true" tabindex="-1"></a>b19001 <span class="sc">%&gt;%</span> </span>
<span id="cb122-18"><a href="#cb122-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(variable) <span class="sc">%&gt;%</span> </span>
<span id="cb122-19"><a href="#cb122-19" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">sum_hh_pct =</span> <span class="fu">sum</span>(hh_pct)) <span class="sc">%&gt;%</span></span>
<span id="cb122-20"><a href="#cb122-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> sum_hh_pct, <span class="at">y =</span> variable), <span class="at">labels =</span> income_labels) <span class="sc">+</span></span>
<span id="cb122-21"><a href="#cb122-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb122-22"><a href="#cb122-22" aria-hidden="true" tabindex="-1"></a><span class="co">#  scale_x_continuous(labels = scales::comma) +</span></span>
<span id="cb122-23"><a href="#cb122-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_discrete</span>(<span class="at">labels =</span> income_labels)<span class="sc">+</span></span>
<span id="cb122-24"><a href="#cb122-24" aria-hidden="true" tabindex="-1"></a>  <span class="co">#labs(x = "Number of Households", y = "Income Level") +</span></span>
<span id="cb122-25"><a href="#cb122-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="co">#+</span></span>
<span id="cb122-26"><a href="#cb122-26" aria-hidden="true" tabindex="-1"></a>  <span class="co">#geom_label(aes(label = income_labels), y = 0.5, fill = "white", color = "black")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a>il_acs_state <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(</span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">"state"</span>,</span>
<span id="cb123-3"><a href="#cb123-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">table =</span> <span class="fu">c</span>(<span class="st">"B19001"</span>),</span>
<span id="cb123-4"><a href="#cb123-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-5"><a href="#cb123-5" aria-hidden="true" tabindex="-1"></a> <span class="co"># variables = c("B19001_001", "B25003_001", "B25003_002"),</span></span>
<span id="cb123-6"><a href="#cb123-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">state =</span> <span class="st">"IL"</span></span>
<span id="cb123-7"><a href="#cb123-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb123-8"><a href="#cb123-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-9"><a href="#cb123-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-10"><a href="#cb123-10" aria-hidden="true" tabindex="-1"></a>il_household_income <span class="ot">&lt;-</span> il_acs_state <span class="sc">%&gt;%</span> </span>
<span id="cb123-11"><a href="#cb123-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>moe) <span class="sc">%&gt;%</span> </span>
<span id="cb123-12"><a href="#cb123-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total =</span> <span class="dv">4884061</span>,</span>
<span id="cb123-13"><a href="#cb123-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">hh_income_pct =</span> estimate<span class="sc">/</span>total<span class="sc">*</span><span class="dv">100</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb123-14"><a href="#cb123-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(variable <span class="sc">!=</span> <span class="st">"B19001_001"</span>)</span>
<span id="cb123-15"><a href="#cb123-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-16"><a href="#cb123-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-17"><a href="#cb123-17" aria-hidden="true" tabindex="-1"></a>il_data_decile <span class="ot">&lt;-</span> il_household_income <span class="sc">%&gt;%</span></span>
<span id="cb123-18"><a href="#cb123-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(HH_income <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb123-19"><a href="#cb123-19" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(<span class="fu">ntile</span>(HH_income, <span class="dv">10</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb123-20"><a href="#cb123-20" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">work_from_home_pct =</span> <span class="fu">mean</span>(work_from_home_pct))</span>
<span id="cb123-21"><a href="#cb123-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-22"><a href="#cb123-22" aria-hidden="true" tabindex="-1"></a>il_acs_county_AWM <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(</span>
<span id="cb123-23"><a href="#cb123-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">"county"</span>,</span>
<span id="cb123-24"><a href="#cb123-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">table =</span> <span class="fu">c</span>(<span class="st">"B19001"</span>),</span>
<span id="cb123-25"><a href="#cb123-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-26"><a href="#cb123-26" aria-hidden="true" tabindex="-1"></a> <span class="co"># variables = c("B19001_001", "B25003_001", "B25003_002"),</span></span>
<span id="cb123-27"><a href="#cb123-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">state =</span> <span class="st">"IL"</span></span>
<span id="cb123-28"><a href="#cb123-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb123-29"><a href="#cb123-29" aria-hidden="true" tabindex="-1"></a><span class="co"># changed from variables = to table = and chose one table. </span></span>
<span id="cb123-30"><a href="#cb123-30" aria-hidden="true" tabindex="-1"></a><span class="co"># need to pivot this table wider</span></span>
<span id="cb123-31"><a href="#cb123-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-32"><a href="#cb123-32" aria-hidden="true" tabindex="-1"></a>il_acs_county_AWM <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>moe) <span class="sc">%&gt;%</span> <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> <span class="st">"variable"</span>, <span class="at">values_from =</span> <span class="st">"estimate"</span>)</span>
<span id="cb123-33"><a href="#cb123-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-34"><a href="#cb123-34" aria-hidden="true" tabindex="-1"></a>il_acs_county <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(</span>
<span id="cb123-35"><a href="#cb123-35" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">"county"</span>,</span>
<span id="cb123-36"><a href="#cb123-36" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="fu">c</span>(<span class="st">"B19001_001"</span>, <span class="st">"B25003_001"</span>, <span class="st">"B25003_002"</span>),</span>
<span id="cb123-37"><a href="#cb123-37" aria-hidden="true" tabindex="-1"></a>  <span class="at">state =</span> <span class="st">"IL"</span>,</span>
<span id="cb123-38"><a href="#cb123-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="st">"wide"</span></span>
<span id="cb123-39"><a href="#cb123-39" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb123-40"><a href="#cb123-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-41"><a href="#cb123-41" aria-hidden="true" tabindex="-1"></a>il_data <span class="ot">&lt;-</span> il_acs_county <span class="sc">%&gt;%</span></span>
<span id="cb123-42"><a href="#cb123-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(GEOID, NAME, B19001_001E, B25003_001E, B25003_002E) <span class="sc">%&gt;%</span></span>
<span id="cb123-43"><a href="#cb123-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">HH_income =</span> B19001_001E,</span>
<span id="cb123-44"><a href="#cb123-44" aria-hidden="true" tabindex="-1"></a>         <span class="at">housing_units =</span> B25003_001E,</span>
<span id="cb123-45"><a href="#cb123-45" aria-hidden="true" tabindex="-1"></a>         <span class="at">work_from_home =</span> B25003_002E) <span class="sc">%&gt;%</span></span>
<span id="cb123-46"><a href="#cb123-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">work_from_home_pct =</span> work_from_home <span class="sc">/</span> housing_units <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb123-47"><a href="#cb123-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-48"><a href="#cb123-48" aria-hidden="true" tabindex="-1"></a>il_data_decile <span class="ot">&lt;-</span> il_data <span class="sc">%&gt;%</span></span>
<span id="cb123-49"><a href="#cb123-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(HH_income <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb123-50"><a href="#cb123-50" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(<span class="fu">ntile</span>(HH_income, <span class="dv">10</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb123-51"><a href="#cb123-51" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">work_from_home_pct =</span> <span class="fu">mean</span>(work_from_home_pct))</span>
<span id="cb123-52"><a href="#cb123-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-53"><a href="#cb123-53" aria-hidden="true" tabindex="-1"></a>il_data_decile <span class="co"># breaks table</span></span>
<span id="cb123-54"><a href="#cb123-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-55"><a href="#cb123-55" aria-hidden="true" tabindex="-1"></a>il_data_decile <span class="ot">&lt;-</span> il_data <span class="sc">%&gt;%</span></span>
<span id="cb123-56"><a href="#cb123-56" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(HH_income <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb123-57"><a href="#cb123-57" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(<span class="fu">ntile</span>(HH_income, <span class="dv">10</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb123-58"><a href="#cb123-58" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">work_from_home_pct =</span> <span class="fu">mean</span>(work_from_home_pct)) <span class="sc">%&gt;%</span> </span>
<span id="cb123-59"><a href="#cb123-59" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb123-60"><a href="#cb123-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-61"><a href="#cb123-61" aria-hidden="true" tabindex="-1"></a>il_data_decile</span>
<span id="cb123-62"><a href="#cb123-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-63"><a href="#cb123-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-64"><a href="#cb123-64" aria-hidden="true" tabindex="-1"></a><span class="co"># chat gpt gave me too many steps and caused problems. Not quite trust worthy. Also dropped variable and didn't ungroup. still impressive. </span></span>
<span id="cb123-65"><a href="#cb123-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-66"><a href="#cb123-66" aria-hidden="true" tabindex="-1"></a>il_data <span class="ot">&lt;-</span> il_acs_county <span class="sc">%&gt;%</span></span>
<span id="cb123-67"><a href="#cb123-67" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(GEOID, NAME, B19001_001E, B25003_001E, B25003_002E) <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">HH_income =</span> B19001_001E,</span>
<span id="cb123-68"><a href="#cb123-68" aria-hidden="true" tabindex="-1"></a>         <span class="at">housing_units =</span> B25003_001E,</span>
<span id="cb123-69"><a href="#cb123-69" aria-hidden="true" tabindex="-1"></a>         <span class="at">work_from_home =</span> B25003_002E) <span class="sc">%&gt;%</span></span>
<span id="cb123-70"><a href="#cb123-70" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">work_from_home_pct =</span> work_from_home <span class="sc">/</span> housing_units <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb123-71"><a href="#cb123-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-72"><a href="#cb123-72" aria-hidden="true" tabindex="-1"></a><span class="do">## bar graph of perccentage of people who worked from home for each income decile</span></span>
<span id="cb123-73"><a href="#cb123-73" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">ntile</span>(HH_income, <span class="dv">10</span>), <span class="at">y =</span> work_from_home_pct)) <span class="sc">+</span></span>
<span id="cb123-74"><a href="#cb123-74" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="fu">aes</span>(<span class="at">fill =</span> <span class="fu">factor</span>(<span class="fu">ntile</span>(HH_income, <span class="dv">10</span>)))) <span class="sc">+</span></span>
<span id="cb123-75"><a href="#cb123-75" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set1"</span>) <span class="sc">+</span></span>
<span id="cb123-76"><a href="#cb123-76" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Income decile"</span>, <span class="at">y =</span> <span class="st">"Percentage who worked from home"</span>) <span class="sc">+</span></span>
<span id="cb123-77"><a href="#cb123-77" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>onetr package <a href="https://cran.r-project.org/web/packages/acs/acs.pdf">cran.r</a></p>
<p>waiting for credentials and password</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("ONETr")</span></span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ONETr)</span>
<span id="cb124-3"><a href="#cb124-3" aria-hidden="true" tabindex="-1"></a><span class="fu">setCreds</span>(<span class="st">"work_from_home_reser"</span>, <span class="st">"6865xvg"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="acs-2019-5-year-data---original-download" class="level2">
<h2 class="anchored" data-anchor-id="acs-2019-5-year-data---original-download">ACS 2019 5-year Data - Original Download</h2>
<p>First download that had 2019 and 2021 data together. Then filtered for just 2019. Will probably delete. If anything, the 2019 data needs to be redownloaded if we do use it to add a few variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a>ddi <span class="ot">&lt;-</span> <span class="fu">read_ipums_ddi</span>(<span class="st">"usa_00006.xml"</span>)</span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_ipums_micro</span>(ddi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Use of data from IPUMS USA is subject to conditions including that users should
cite the data appropriately. Use command `ipums_conditions()` for more details.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>data2019 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(STATEFIP, REGION)) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(YEAR <span class="sc">==</span> <span class="st">"2019"</span>)</span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(data)</span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 621,164 observations for ACS2021 5-Year sample</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="descriptive-statistics" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-statistics">Descriptive Statistics</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data2019</span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(data2019)</span>
<span id="cb128-3"><a href="#cb128-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>EMPSTAT) <span class="co"># unweighted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1      2      3 
114042 303672  17088 196119 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>LABFORCE) <span class="co"># unweighted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1      2 
114042 196119 320760 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>CLASSWKR)<span class="co"># unweighted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1      2 
254277  33888 342756 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(<span class="at">df =</span> data, <span class="at">variable =</span> LABFORCE, <span class="at">weight =</span> PERWT )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 x 5
  Response                   Frequency Percent `Valid Percent` `Cumulative Per~`
  &lt;fct&gt;                          &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt;             &lt;dbl&gt;
1 N/A                          2551692    20.0            20.0              20.0
2 No, not in the labor force   3558081    27.9            27.9              47.8
3 Yes, in the labor force      6660858    52.2            52.2             100  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="fu">crosstab</span>(data, <span class="at">x=</span>MULTYEAR, <span class="at">y =</span> LABFORCE, <span class="at">weight =</span> PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 x 5
  MULTYEAR `N/A` `No, not in the labor force` `Yes, in the labor force`       n
     &lt;dbl&gt; &lt;dbl&gt;                        &lt;dbl&gt;                     &lt;dbl&gt;   &lt;dbl&gt;
1     2015  20.4                         27.7                      51.8 2574088
2     2016  20.1                         27.8                      52.1 2563265
3     2017  20.0                         27.8                      52.1 2568647
4     2018  19.7                         27.9                      52.4 2547807
5     2019  19.6                         28.1                      52.3 2516824</code></pre>
</div>
<div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(data, EMPSTAT, PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 x 5
  Response           Frequency Percent `Valid Percent` `Cumulative Percent`
  &lt;fct&gt;                  &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt;                &lt;dbl&gt;
1 N/A                  2551692   20.0            20.0                  20.0
2 Employed             6268818   49.1            49.1                  69.1
3 Unemployed            392040    3.07            3.07                 72.1
4 Not in labor force   3558081   27.9            27.9                 100  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="fu">crosstab</span>(data, <span class="at">x=</span>MULTYEAR, <span class="at">y =</span> EMPSTAT, <span class="at">weight =</span> PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 x 6
  MULTYEAR `N/A` Employed Unemployed `Not in labor force`       n
     &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;                &lt;dbl&gt;   &lt;dbl&gt;
1     2015  20.4     48.3       3.58                 27.7 2574088
2     2016  20.1     48.8       3.28                 27.8 2563265
3     2017  20.0     48.9       3.17                 27.8 2568647
4     2018  19.7     49.6       2.85                 27.9 2547807
5     2019  19.6     49.8       2.45                 28.1 2516824</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="co">#library(srvyr)</span></span>
<span id="cb142-2"><a href="#cb142-2" aria-hidden="true" tabindex="-1"></a><span class="co">#library(survey)</span></span>
<span id="cb142-3"><a href="#cb142-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb142-4"><a href="#cb142-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">PWSTATE2_clean =</span> <span class="fu">as_factor</span>(<span class="fu">lbl_na_if</span>(PWSTATE2, <span class="sc">~</span>.val <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb142-5"><a href="#cb142-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">inctot_decile =</span> <span class="fu">ntile</span>(INCTOT, <span class="dv">10</span>),</span>
<span id="cb142-6"><a href="#cb142-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">incwage_decile =</span> <span class="fu">ntile</span>(INCWAGE, <span class="dv">10</span>),</span>
<span id="cb142-7"><a href="#cb142-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">incearn_decile =</span><span class="fu">ntile</span>(INCEARN, <span class="dv">10</span>))  <span class="co">#adds a variable to indicate which decile an observation falls within</span></span>
<span id="cb142-8"><a href="#cb142-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb142-9"><a href="#cb142-9" aria-hidden="true" tabindex="-1"></a><span class="co">#attempt &lt;- svydesign(id=~row(data) , weights=data$PERWT, data=data)</span></span>
<span id="cb142-10"><a href="#cb142-10" aria-hidden="true" tabindex="-1"></a><span class="co">#a &lt;- svyquantile(design=attempt, quantiles = seq(0,1, by=0.1))</span></span>
<span id="cb142-11"><a href="#cb142-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb142-12"><a href="#cb142-12" aria-hidden="true" tabindex="-1"></a><span class="co">#quantile(x, probs = seq(0, 1, 1/10))    # Deciles</span></span>
<span id="cb142-13"><a href="#cb142-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb142-14"><a href="#cb142-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCEARN))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  -7600       0    2294   28922   40484  943857 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb144"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb144-1"><a href="#cb144-1" aria-hidden="true" tabindex="-1"></a><span class="co"># weighted_breaksummary &lt;- data %&gt;% </span></span>
<span id="cb144-2"><a href="#cb144-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   #srvyr::as_survey(weights = PERWT) %&gt;%</span></span>
<span id="cb144-3"><a href="#cb144-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   group_by(incearn_decile) %&gt;%</span></span>
<span id="cb144-4"><a href="#cb144-4" aria-hidden="true" tabindex="-1"></a><span class="co">#   summarize(decile_min = min(INCEARN),</span></span>
<span id="cb144-5"><a href="#cb144-5" aria-hidden="true" tabindex="-1"></a><span class="co">#             decile_max = max(INCEARN)</span></span>
<span id="cb144-6"><a href="#cb144-6" aria-hidden="true" tabindex="-1"></a><span class="co">#             ) </span></span>
<span id="cb144-7"><a href="#cb144-7" aria-hidden="true" tabindex="-1"></a><span class="co"># weighted_breaksummary # not actually weighted yet because I used incearn_decile which was created without weighing the data...</span></span>
<span id="cb144-8"><a href="#cb144-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb144-9"><a href="#cb144-9" aria-hidden="true" tabindex="-1"></a>unweighted_breaksummary <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb144-10"><a href="#cb144-10" aria-hidden="true" tabindex="-1"></a>  <span class="co">#srvyr::as_survey(weights = c(PERWT)) %&gt;%</span></span>
<span id="cb144-11"><a href="#cb144-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(incearn_decile) <span class="sc">%&gt;%</span></span>
<span id="cb144-12"><a href="#cb144-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">decile_min =</span> <span class="fu">min</span>(INCEARN),</span>
<span id="cb144-13"><a href="#cb144-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">decile_max =</span> <span class="fu">max</span>(INCEARN)</span>
<span id="cb144-14"><a href="#cb144-14" aria-hidden="true" tabindex="-1"></a>            ) </span>
<span id="cb144-15"><a href="#cb144-15" aria-hidden="true" tabindex="-1"></a>unweighted_breaksummary <span class="co"># NOT WEIGHTED!!!!</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 x 3
   incearn_decile          decile_min           decile_max
            &lt;int&gt;           &lt;dbl+lbl&gt;            &lt;dbl+lbl&gt;
 1              1 -7600                    0 [No earnings]
 2              2     0 [No earnings]      0 [No earnings]
 3              3     0 [No earnings]      0 [No earnings]
 4              4     0 [No earnings]      0 [No earnings]
 5              5     0 [No earnings]   2294              
 6              6  2294                15980              
 7              7 15980                31428              
 8              8 31428                50072              
 9              9 50072                80000              
10             10 80000               943857              </code></pre>
</div>
<div class="sourceCode cell-code" id="cb146"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb146-1"><a href="#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="co"># histogram of total income</span></span>
<span id="cb146-2"><a href="#cb146-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>INCEARN, <span class="at">breaks =</span> <span class="dv">60</span>) <span class="co"># unweighted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb147-2"><a href="#cb147-2" aria-hidden="true" tabindex="-1"></a> <span class="co"># filter (INCTOT &lt; 400000) %&gt;% </span></span>
<span id="cb147-3"><a href="#cb147-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>INCEARN)) <span class="sc">+</span> </span>
<span id="cb147-4"><a href="#cb147-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span>  <span class="dv">60</span>) <span class="sc">+</span> </span>
<span id="cb147-5"><a href="#cb147-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> <span class="fu">label_dollar</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb148"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb148-1"><a href="#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(data, incearn_decile, <span class="at">weight =</span> PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 x 5
   Response Frequency Percent `Valid Percent` `Cumulative Percent`
   &lt;fct&gt;        &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt;                &lt;dbl&gt;
 1 1          1265633    9.91            9.91                 9.91
 2 2          1267579    9.93            9.93                19.8 
 3 3          1241998    9.73            9.73                29.6 
 4 4          1250473    9.79            9.79                39.4 
 5 5          1254825    9.83            9.83                49.2 
 6 6          1278799   10.0            10.0                 59.2 
 7 7          1384325   10.8            10.8                 70.0 
 8 8          1298145   10.2            10.2                 80.2 
 9 9          1262776    9.89            9.89                90.1 
10 10         1266078    9.91            9.91               100   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb150"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb150-1"><a href="#cb150-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>decile <span class="ot">&lt;-</span> <span class="fu">ntile</span>(data<span class="sc">$</span>INCEARN, <span class="dv">10</span>)</span>
<span id="cb150-2"><a href="#cb150-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb150-3"><a href="#cb150-3" aria-hidden="true" tabindex="-1"></a><span class="co"># from weights() package</span></span>
<span id="cb150-4"><a href="#cb150-4" aria-hidden="true" tabindex="-1"></a><span class="fu">wtd.hist</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCEARN), <span class="at">breaks =</span> <span class="dv">40</span>, <span class="at">weight =</span> data<span class="sc">$</span>PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_files/figure-html/unnamed-chunk-15-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb151"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wtd.hist</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCEARN), <span class="at">weight =</span> data<span class="sc">$</span>PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_files/figure-html/unnamed-chunk-15-4.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb152"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb152-1"><a href="#cb152-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data_svy = svydesign(~1, #no clusters</span></span>
<span id="cb152-2"><a href="#cb152-2" aria-hidden="true" tabindex="-1"></a><span class="co">#                      data = data, </span></span>
<span id="cb152-3"><a href="#cb152-3" aria-hidden="true" tabindex="-1"></a><span class="co">#                      weight=~PERWT)</span></span>
<span id="cb152-4"><a href="#cb152-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb152-5"><a href="#cb152-5" aria-hidden="true" tabindex="-1"></a>  <span class="co">#svyquantile(~INCTOT,data_svy, </span></span>
<span id="cb152-6"><a href="#cb152-6" aria-hidden="true" tabindex="-1"></a>   <span class="co">#                          quantiles=seq(0.1, 0.9, 0.1))</span></span>
<span id="cb152-7"><a href="#cb152-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb152-8"><a href="#cb152-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x=</span>INCEARN)) <span class="sc">+</span> </span>
<span id="cb152-9"><a href="#cb152-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span>  <span class="dv">30</span>) <span class="sc">+</span> </span>
<span id="cb152-10"><a href="#cb152-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> <span class="fu">label_dollar</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_files/figure-html/unnamed-chunk-15-5.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb153"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb153-1"><a href="#cb153-1" aria-hidden="true" tabindex="-1"></a>noOCCSOC<span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(OCCSOC <span class="sc">==</span> <span class="dv">0</span>) <span class="co">#98205 with occsoc=0</span></span>
<span id="cb153-2"><a href="#cb153-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(noOCCSOC<span class="sc">$</span>EMPSTAT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      3 
114042 136672 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb155"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb155-1"><a href="#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="co">#98% of the people without Occupation codes are not in the labor force. Makes sense. </span></span>
<span id="cb155-2"><a href="#cb155-2" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(<span class="at">df =</span> noOCCSOC, <span class="at">variable =</span> EMPSTAT, <span class="at">weight =</span> PERWT )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 x 5
  Response           Frequency Percent `Valid Percent` `Cumulative Percent`
  &lt;fct&gt;                  &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt;                &lt;dbl&gt;
1 N/A                  2551692    50.0            50.0                 50.0
2 Not in labor force   2546650    50.0            50.0                100  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb157"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb157-1"><a href="#cb157-1" aria-hidden="true" tabindex="-1"></a>data2<span class="ot">&lt;-</span> <span class="fu">anti_join</span>(data,noOCCSOC)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Joining, by = c("YEAR", "MULTYEAR", "SAMPLE", "SERIAL", "CBSERIAL", "HHWT",
"CLUSTER", "COUNTYFIP", "CITY", "PUMA", "STRATA", "GQ", "HHINCOME", "PERNUM",
"PERWT", "SEX", "AGE", "RACE", "RACED", "EDUC", "EDUCD", "EMPSTAT", "EMPSTATD",
"LABFORCE", "CLASSWKR", "CLASSWKRD", "OCC", "OCC2010", "OCCSOC", "IND",
"INCTOT", "FTOTINC", "INCWAGE", "INCEARN", "OCCSCORE", "PWSTATE2", "PWCOUNTY",
"PWTYPE", "TRANWORK", "TRANTIME", "PWSTATE2_clean", "inctot_decile",
"incwage_decile", "incearn_decile", "decile")</code></pre>
</div>
<div class="sourceCode cell-code" id="cb159"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb159-1"><a href="#cb159-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 362787 obs</span></span>
<span id="cb159-2"><a href="#cb159-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-3"><a href="#cb159-3" aria-hidden="true" tabindex="-1"></a>data2 <span class="ot">&lt;-</span> data2 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(AGE<span class="sc">&gt;=</span><span class="dv">25</span>)</span>
<span id="cb159-4"><a href="#cb159-4" aria-hidden="true" tabindex="-1"></a><span class="co">#316399 obs</span></span>
<span id="cb159-5"><a href="#cb159-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-6"><a href="#cb159-6" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(<span class="at">df =</span> data2, <span class="at">variable =</span> EMPSTAT, <span class="at">weight =</span> PERWT )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 x 5
  Response           Frequency Percent `Valid Percent` `Cumulative Percent`
  &lt;fct&gt;                  &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt;                &lt;dbl&gt;
1 Employed             5467895   83.4            83.4                  83.4
2 Unemployed            273188    4.17            4.17                 87.5
3 Not in labor force    817413   12.5            12.5                 100  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb161"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb161-1"><a href="#cb161-1" aria-hidden="true" tabindex="-1"></a><span class="fu">crosstab</span>(data2, <span class="at">x=</span>MULTYEAR, <span class="at">y =</span> LABFORCE, <span class="at">weight =</span> PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 x 4
  MULTYEAR `No, not in the labor force` `Yes, in the labor force`       n
     &lt;dbl&gt;                        &lt;dbl&gt;                     &lt;dbl&gt;   &lt;dbl&gt;
1     2015                         12.5                      87.5 1313119
2     2016                         12.7                      87.3 1314296
3     2017                         12.5                      87.5 1315474
4     2018                         12.4                      87.6 1317813
5     2019                         12.3                      87.7 1297794</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb163"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb163-1"><a href="#cb163-1" aria-hidden="true" tabindex="-1"></a><span class="co">#telework csv uses data from Dingle and Nieman</span></span>
<span id="cb163-2"><a href="#cb163-2" aria-hidden="true" tabindex="-1"></a><span class="co"># https://github.com/jdingel/DingelNeiman-workathome/blob/master/occ_manual_scores/input/Teleworkable_BNJDopinion.csv</span></span>
<span id="cb163-3"><a href="#cb163-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb163-4"><a href="#cb163-4" aria-hidden="true" tabindex="-1"></a>telework<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"teleworkable2010_v2.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1810 Columns: 5
-- Column specification --------------------------------------------------------
Delimiter: ","
chr (3): onetsoc_6digits, major_code_label, major_code_2digits
dbl (2): Count of teleworkable, teleworkable

i Use `spec()` to retrieve the full column specification for this data.
i Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb165"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb165-1"><a href="#cb165-1" aria-hidden="true" tabindex="-1"></a><span class="co">#telework&lt;- read_csv("teleworkable2010.csv")</span></span>
<span id="cb165-2"><a href="#cb165-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb165-3"><a href="#cb165-3" aria-hidden="true" tabindex="-1"></a><span class="co"># causes problems for any occupation code that has XX in it!! </span></span>
<span id="cb165-4"><a href="#cb165-4" aria-hidden="true" tabindex="-1"></a><span class="co">#data2$OCCSOC_num &lt;- as.numeric(data2$OCCSOC)</span></span>
<span id="cb165-5"><a href="#cb165-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb165-6"><a href="#cb165-6" aria-hidden="true" tabindex="-1"></a>innerjoined<span class="ot">&lt;-</span><span class="fu">inner_join</span>(data2, telework, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"OCCSOC"</span><span class="ot">=</span> <span class="st">"onetsoc_6digits"</span>))</span>
<span id="cb165-7"><a href="#cb165-7" aria-hidden="true" tabindex="-1"></a><span class="co"># ___ obs in innerjoin</span></span>
<span id="cb165-8"><a href="#cb165-8" aria-hidden="true" tabindex="-1"></a><span class="co"># __ obs after updating teleworkable2010 file with broader 5digit codes that 6digit 0</span></span>
<span id="cb165-9"><a href="#cb165-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb165-10"><a href="#cb165-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 312350 obs after adding 5digitsX and 4digitsXX codes to teleworkable.</span></span>
<span id="cb165-11"><a href="#cb165-11" aria-hidden="true" tabindex="-1"></a><span class="co"># teleworkable values are an average of occupations with same first 5 digits and first 4 digits. </span></span>
<span id="cb165-12"><a href="#cb165-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb165-13"><a href="#cb165-13" aria-hidden="true" tabindex="-1"></a>leftjoined<span class="ot">&lt;-</span><span class="fu">left_join</span>(data2, telework, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"OCCSOC"</span><span class="ot">=</span> <span class="st">"onetsoc_6digits"</span>))</span>
<span id="cb165-14"><a href="#cb165-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb165-15"><a href="#cb165-15" aria-hidden="true" tabindex="-1"></a><span class="co">#innerjoined&lt;-inner_join(data2, telework, by = c("OCCSOC_num"= "BroadGroupCode"))</span></span>
<span id="cb165-16"><a href="#cb165-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb165-17"><a href="#cb165-17" aria-hidden="true" tabindex="-1"></a><span class="co">#leftjoined&lt;-left_join(data2, telework, by = c("OCCSOC_num"= "BroadGroupCode"))</span></span>
<span id="cb165-18"><a href="#cb165-18" aria-hidden="true" tabindex="-1"></a><span class="co"># keeps all observations in data 2 even if they don't match</span></span>
<span id="cb165-19"><a href="#cb165-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb165-20"><a href="#cb165-20" aria-hidden="true" tabindex="-1"></a><span class="co">#antijoin &lt;-anti_join(data2, telework, by = c("OCCSOC_num"= "onetsoc_6digits"))</span></span>
<span id="cb165-21"><a href="#cb165-21" aria-hidden="true" tabindex="-1"></a><span class="co"># 158525. Many were aggregated to 5digits with 6digit as 0.</span></span>
<span id="cb165-22"><a href="#cb165-22" aria-hidden="true" tabindex="-1"></a><span class="co"># 91403 obs after updating teleworkable file to 5digits with 6digit as 0</span></span>
<span id="cb165-23"><a href="#cb165-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb165-24"><a href="#cb165-24" aria-hidden="true" tabindex="-1"></a><span class="co">#couldnt use _num version due to XX in values.</span></span>
<span id="cb165-25"><a href="#cb165-25" aria-hidden="true" tabindex="-1"></a>antijoin <span class="ot">&lt;-</span><span class="fu">anti_join</span>(data2, telework, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"OCCSOC"</span><span class="ot">=</span> <span class="st">"onetsoc_6digits"</span>))</span>
<span id="cb165-26"><a href="#cb165-26" aria-hidden="true" tabindex="-1"></a><span class="co"># 50,584 obs after adding 5digitsX and 4digitsXX and 5digits with sixth as 0 to csv file</span></span>
<span id="cb165-27"><a href="#cb165-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb165-28"><a href="#cb165-28" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(antijoin<span class="sc">$</span>OCCSOC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "999920" "291210" "254022" "211019" "537065" "413091" "151252" "211029"
 [9] "131082" "514XXX" "1721YY" "311131" "251000" "299000" "533054" "353023"
[17] "292042" "272099" "533051" "311122" "291292" "533052" "151211" "519160"
[25] "311121" "292072" "31113X" "151299" "151251" "151253" "151230" "273092"
[33] "472XXX" "1940YY" "531000" "391000" "419099" "399099" "439XXX" "151244"
[41] "253041" "151241" "151254" "15124X" "151212" "533053" "513099" "273023"
[49] "291240" "212099" "292043" "434XXX" "434YYY" "559830" "113012" "291291"
[57] "113013" "533099" "273099" "151255" "432099" "195010" "4750YY" "232099"
[65] "291299" "193034" "359099" "339094" "475032" "151221" "193033" "453031"
[73] "272091"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb167"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb167-1"><a href="#cb167-1" aria-hidden="true" tabindex="-1"></a><span class="co"># down to 73 after adding 5digitsX and 4digitsXX and 5digits with sixth as 0 to csv file</span></span>
<span id="cb167-2"><a href="#cb167-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb167-3"><a href="#cb167-3" aria-hidden="true" tabindex="-1"></a><span class="co">#table(joined$Teleworkable)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="xiaoyans-merging-notes" class="level2">
<h2 class="anchored" data-anchor-id="xiaoyans-merging-notes">Xiaoyan’s Merging Notes</h2>
<p>Code chunk below is my attempt to manually recode items that didn’t match. I think I have an excel file of OCCSOC codes that should match almost completely.</p>
<p><em>Double check</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb168"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb168-1"><a href="#cb168-1" aria-hidden="true" tabindex="-1"></a>data2021 <span class="sc">%&gt;%</span> </span>
<span id="cb168-2"><a href="#cb168-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(OCCSOC <span class="sc">&gt;</span><span class="dv">0</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb168-3"><a href="#cb168-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">telworkable =</span> <span class="fu">case_when</span>(</span>
<span id="cb168-4"><a href="#cb168-4" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"113013"</span> <span class="sc">~</span> ,</span>
<span id="cb168-5"><a href="#cb168-5" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"131081"</span> <span class="sc">~</span> ,</span>
<span id="cb168-6"><a href="#cb168-6" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"151255"</span> <span class="sc">~</span> ,</span>
<span id="cb168-7"><a href="#cb168-7" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"195010"</span> <span class="sc">~</span> ,</span>
<span id="cb168-8"><a href="#cb168-8" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"211019"</span> <span class="sc">~</span> ,</span>
<span id="cb168-9"><a href="#cb168-9" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"211029"</span> <span class="sc">~</span> ,    </span>
<span id="cb168-10"><a href="#cb168-10" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"211092"</span> <span class="sc">~</span> ,</span>
<span id="cb168-11"><a href="#cb168-11" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"211093"</span> <span class="sc">~</span> ,</span>
<span id="cb168-12"><a href="#cb168-12" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"212099"</span> <span class="sc">~</span> ,</span>
<span id="cb168-13"><a href="#cb168-13" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"232099"</span> <span class="sc">~</span> ,</span>
<span id="cb168-14"><a href="#cb168-14" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"2504022"</span> <span class="sc">~</span> <span class="st">"0"</span>, <span class="co"># libararians and media collections specialists. </span></span>
<span id="cb168-15"><a href="#cb168-15" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"272091"</span> <span class="sc">~</span> , <span class="co"># disc jockets. Was 272099</span></span>
<span id="cb168-16"><a href="#cb168-16" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"272099"</span> <span class="sc">~</span> <span class="st">"RECODED"</span>,</span>
<span id="cb168-17"><a href="#cb168-17" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"273092"</span> <span class="sc">~</span>  <span class="st">"1"</span>, <span class="co">#court reporters and captioners </span></span>
<span id="cb168-18"><a href="#cb168-18" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"273099"</span> <span class="sc">~</span> <span class="st">"1"</span>, <span class="co"># media and comunication workers, all other</span></span>
<span id="cb168-19"><a href="#cb168-19" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"311122"</span> <span class="sc">~</span> <span class="st">"0"</span>,   <span class="co"># personal care aids</span></span>
<span id="cb168-20"><a href="#cb168-20" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"331090"</span> <span class="sc">~</span> <span class="st">"0"</span>,    <span class="co"># healthcare and support specialists </span></span>
<span id="cb168-21"><a href="#cb168-21" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"339094"</span> <span class="sc">~</span> ,    </span>
<span id="cb168-22"><a href="#cb168-22" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"359099"</span> <span class="sc">~</span> ,    </span>
<span id="cb168-23"><a href="#cb168-23" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"413091"</span> <span class="sc">~</span> <span class="st">"0"</span>,</span>
<span id="cb168-24"><a href="#cb168-24" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"419099"</span> <span class="sc">~</span>  <span class="st">"0"</span>, <span class="co"># sales and related workers all other</span></span>
<span id="cb168-25"><a href="#cb168-25" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"432099"</span> <span class="sc">~</span> <span class="st">"0.5"</span>, <span class="co"># communications equipment operators, all other</span></span>
<span id="cb168-26"><a href="#cb168-26" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"4330XX"</span> <span class="sc">~</span> <span class="st">"0.5"</span>, <span class="co"># 43 is office and admin support</span></span>
<span id="cb168-27"><a href="#cb168-27" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"513099"</span> <span class="sc">~</span> <span class="st">"0"</span>, <span class="co">#food processing workers</span></span>
<span id="cb168-28"><a href="#cb168-28" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"533099"</span> <span class="sc">~</span>  <span class="st">"0"</span>, <span class="co"># motor vehicle operators</span></span>
<span id="cb168-29"><a href="#cb168-29" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"537065"</span> <span class="sc">~</span> <span class="st">"0"</span>, <span class="co"># stockers and order fillers</span></span>
<span id="cb168-30"><a href="#cb168-30" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"551010"</span> <span class="sc">~</span> <span class="st">"0"</span>, <span class="co"># miltary </span></span>
<span id="cb168-31"><a href="#cb168-31" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"552020"</span> <span class="sc">~</span> <span class="st">"0"</span>, <span class="co"># military</span></span>
<span id="cb168-32"><a href="#cb168-32" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"553010"</span> <span class="sc">~</span> <span class="st">"0"</span>, <span class="co"># military</span></span>
<span id="cb168-33"><a href="#cb168-33" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"559830"</span> <span class="sc">~</span> <span class="st">"0"</span>, <span class="co"># military</span></span>
<span id="cb168-34"><a href="#cb168-34" aria-hidden="true" tabindex="-1"></a><span class="cn">TRUE</span> <span class="sc">~</span> <span class="fu">as.character</span>(OCCSOC))</span>
<span id="cb168-35"><a href="#cb168-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb168-36"><a href="#cb168-36" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>****merge****</p>
<p>merge m:1 occsoc using “/Users/xiaoyanhu/Desktop/crosswalk.dta”</p>
<p>*IL has but DN no: 29, merge==2</p>
<p>*113013 Facilities Managers</p>
<p>*131082 Project Management Specialists</p>
<p>*151255 Web And Digital Interface Designers</p>
<p>*195010 Occupational Health And Safety Specialists And Technicians</p>
<p>*211019 Counselors, All Other</p>
<p>*211029 Social Workers All Other</p>
<p>*211092 Probation Officers and Correctional Treatment Specialists</p>
<p>*211093 Social and Human Service Assistants</p>
<p>*212099 Religious Workers, All Other</p>
<p>*232099 Legal Support Workers, All Other</p>
<p>*272091 Disc Jockeys, Except Radio</p>
<p>*272099 Entertainers and Performers, Sports and Related Workers, All Other</p>
<p>*273092 Court Reporters And Simultaneous Captioners</p>
<p>*273099 Media And Communications Workers, All Other</p>
<p>*311122 Personal Care Aides</p>
<p>*331090 Miscellaneous First-Line Supervisors, Protective Service Workers</p>
<p>*339094 School Bus Monitors</p>
<p>*359099 Food Preparation and Serving Related Workers, All Other</p>
<p>*413091 Sales Representatives Of Services, Except Advertising, Insurance, Financial Services, And Travel</p>
<p>*419099 Sales and Related Workers, All Other</p>
<p>*432099 Communications Equipment Operators, All Other</p>
<p>*4330XX Other Financial Clerks</p>
<p>*513099 Food Processing Workers, All&nbsp;Other</p>
<p>*533099 Motor Vehicle Operators, All Other</p>
<p>*537065 Stockers And Order Fillers</p>
<p>*551010 Military Officer Special and Tactical Operations Leaders</p>
<p>*552010 First-Line Enlisted Military Supervisors</p>
<p>*553010 Military Enlisted Tactical Operations and Air/Weapons Specialists and Crew Members</p>
<p>*559830 Military, Rank Not Specified</p>
<p>*DN has but IL no: 7, merge==1</p>
<p>** AWM - These were 2010 codes that have been changed to 2018 SOC codes</p>
<p>*119061 Funeral Service Managers #Code and Title change to 119171</p>
<p>*119131 Postmasters and Mail Superintendents #Didn’t change, should have been in their file?</p>
<p>*173021 Aerospace Engineering and Operations Technicians</p>
<p>*173022 Civil Engineering Technicians</p>
<p>*232091 Court Reporters</p>
<p>*413099 Energy Brokers</p>
<p>*433041 Gaming Cage Workers</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>