<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Work From Home: Who Can and Who Does?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="WorkFromHome_2019ACS5year_files/libs/clipboard/clipboard.min.js"></script>
<script src="WorkFromHome_2019ACS5year_files/libs/quarto-html/quarto.js"></script>
<script src="WorkFromHome_2019ACS5year_files/libs/quarto-html/popper.min.js"></script>
<script src="WorkFromHome_2019ACS5year_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="WorkFromHome_2019ACS5year_files/libs/quarto-html/anchor.min.js"></script>
<link href="WorkFromHome_2019ACS5year_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="WorkFromHome_2019ACS5year_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="WorkFromHome_2019ACS5year_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="WorkFromHome_2019ACS5year_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="WorkFromHome_2019ACS5year_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Work From Home: Who Can and Who Does?</h1>
<p class="subtitle lead">Using ACS &amp; O*NET Data</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="getting-data" class="level1">
<h1>Getting Data</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reldist)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pollster)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(labelled)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(weights)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tigris)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ipumsr)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="acs-data-notes" class="level1">
<h1>ACS data Notes</h1>
<ul>
<li><p>INCWAGE is topcoded only at the 99.5th percentile within a state. So almost ALL obs should be close their actual income.</p>
<ul>
<li>Incwage coding procedure <a href="https://usa.ipums.org/usa-action/variables/INCWAGE#editing_procedure_section">link</a></li>
</ul></li>
<li><p>INCTOT includes self-employment income, INCWAGE does not.</p>
<ul>
<li>Some industries (e.g.&nbsp;farming) may not be included in sample if using INCWAGE. Does that matter?</li>
<li>Bottom coded at -$19,988, is not top coded</li>
</ul></li>
<li><p>INCEARN includes salaries, wages, and business/farm income. Use this one I think</p>
<ul>
<li><p>INCEARN is made from summing INCWAGE, INCBUS, and INCFARM</p></li>
<li><p>INCEARN is not itself topcoded, but some of the other variables may be, especially for early years of data collection (which don’t apply to us)</p></li>
</ul></li>
</ul>
<section id="year-data" class="level2">
<h2 class="anchored" data-anchor-id="year-data">2021 1-Year Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>ddi <span class="ot">&lt;-</span> <span class="fu">read_ipums_ddi</span>(<span class="st">"C:/Users/aleaw/Box/Fiscal Futures/FY22_Working/WFH/Data/IL_2019_5yrACSlabels_dat.xml"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_ipums_micro</span>(ddi) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Use of data from IPUMS USA is subject to conditions including that users should
cite the data appropriately. Use command `ipums_conditions()` for more details.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 630,921 observations</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="occupation-codes" class="level3">
<h3 class="anchored" data-anchor-id="occupation-codes">Occupation codes</h3>
<p><code>OCC2010</code> is a harmonized occupation coding scheme as broad groups. These are 4 characters long and are the first 4 characters of the longer ONET &amp; SOC codes.</p>
<p><code>OCCSOC</code> is 6 digits long. It is the first 6 digits of 8-digit ONET code.</p>
<ul>
<li>Please note that in some cases the SOC occupation codes are aggregated if they do not have an exact match to a Census occupation code or to preserve confidentiality in cases where the category contained fewer than 10,000 people nationwide.</li>
</ul>
<p><code>LABFORCE</code> for if in labor force. 1 = not in labor force, 2 = in labor force, 0 is NA</p>
<p><code>EMPSTAT</code> and <code>EMPSTATD</code> for employment status (simple and the detailed version). 1=employed, 2=unemployed, 3=not in labor force for empstat, 0 is NA</p>
<p><code>CLASSWKRD</code> might be useful. Contains info on self-employed, wages, salary, etc for class of worker.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>For persons who are unemployed, the data refer to the most recent job if it was within the last 5 years.</p>
</div>
</div>
<p>IPUMS <a href="https://usa.ipums.org/usa/repwt.shtml">link for Survey package</a></p>
<p>IPUMS OCC codes over time <a href="https://usa.ipums.org/usa/volii/occsoc18.shtml">link</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>EMPSTAT) <span class="co"># unweighted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1      2      3 
114042 303672  17088 196119 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">as_factor</span>(EMPSTAT)) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">n=</span><span class="fu">sum</span>(PERWT)) <span class="sc">%&gt;%</span> </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span> n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 x 3
  `as_factor(EMPSTAT)`       n    pct
  &lt;fct&gt;                  &lt;dbl&gt;  &lt;dbl&gt;
1 N/A                  2551692 0.200 
2 Employed             6268818 0.491 
3 Unemployed            392040 0.0307
4 Not in labor force   3558081 0.279 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>LABFORCE) <span class="co"># unweighted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1      2 
114042 196119 320760 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(<span class="fu">as_factor</span>(LABFORCE)) <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">n=</span><span class="fu">sum</span>(PERWT)) <span class="sc">%&gt;%</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span> n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 x 3
  `as_factor(LABFORCE)`            n   pct
  &lt;fct&gt;                        &lt;dbl&gt; &lt;dbl&gt;
1 N/A                        2551692 0.200
2 No, not in the labor force 3558081 0.279
3 Yes, in the labor force    6660858 0.522</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>CLASSWKR)<span class="co"># unweighted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1      2 
254277  33888 342756 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">as_factor</span>(CLASSWKR)) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">n=</span><span class="fu">sum</span>(PERWT)) <span class="sc">%&gt;%</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span> n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 x 3
  `as_factor(CLASSWKR)`       n    pct
  &lt;fct&gt;                   &lt;dbl&gt;  &lt;dbl&gt;
1 N/A                   5192423 0.407 
2 Self-employed          637235 0.0499
3 Works for wages       6940973 0.544 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TRANWORK) <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">sum</span>(PERWT)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 x 2
                                                       TRANWORK       n
                                                      &lt;int+lbl&gt;   &lt;dbl&gt;
 1  0 [N/A]                                                     6618007
 2 10 [Auto, truck, or van]                                     4969545
 3 20 [Motorcycle]                                                 4020
 4 31 [Bus]                                                      224552
 5 34 [Light rail, streetcar, or trolley (Carro público in PR)]    4463
 6 36 [Subway or elevated]                                       203846
 7 37 [Long-distance train or commuter train]                    148217
 8 38 [Taxicab]                                                   19069
 9 39 [Ferryboat]                                                   726
10 50 [Bicycle]                                                   38749
11 60 [Walked only]                                              181545
12 70 [Other]                                                     50290
13 80 [Worked at home]                                           307602</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(<span class="at">df =</span> data, <span class="at">variable =</span> LABFORCE, <span class="at">weight =</span> PERWT )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 x 5
  Response                   Frequency Percent `Valid Percent` `Cumulative Per~`
  &lt;fct&gt;                          &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt;             &lt;dbl&gt;
1 N/A                          2551692    20.0            20.0              20.0
2 No, not in the labor force   3558081    27.9            27.9              47.8
3 Yes, in the labor force      6660858    52.2            52.2             100  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(data, EMPSTAT, PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 x 5
  Response           Frequency Percent `Valid Percent` `Cumulative Percent`
  &lt;fct&gt;                  &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt;                &lt;dbl&gt;
1 N/A                  2551692   20.0            20.0                  20.0
2 Employed             6268818   49.1            49.1                  69.1
3 Unemployed            392040    3.07            3.07                 72.1
4 Not in labor force   3558081   27.9            27.9                 100  </code></pre>
</div>
</div>
<p><em>Unweighted -</em></p>
<p><em>EMPSTAT: 303,672 observations are employed, 17,088 unemployed observations, and 196,229 observations are not in the workforce (114,042 NAs)</em></p>
<p><em>LABFORCE: 320,760 are in labor force, 196,119 are not. (114,042 NAs)</em></p>
<p><em>CLASSWKR: Of these, 342,756 work for wages and 33,888 people are self-employed. (254,277 NA)</em></p>
<p><u><strong>Weighted</strong></u> <strong>-</strong></p>
<p>EMPSTAT: 6,268,818 people are employed (49%), 392,040 people are unemployed(3.01%), and 3,558,081 are not in the labor force (28%). There are 2,551,692 missing values; Same as LABFORCE.</p>
<p>LABFORCE: 6,660,858 people (52%) are in the labor force. 3,668,081 (28%) of people are not in the labor force. 2,551,692 (20%) of observations missing values.</p>
<ul>
<li>employed and unemployed equal number of people in labor force - that’s good</li>
</ul>
<p>Location of primary workplace: 5.8 million people located in Illinois.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># State worked in:</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co">#0=NA, 17=Illinois</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>COUPLETYPE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1      2      3      4 
203215 385046   2525  38342   1793 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>NFAMS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     1      2      3      4      5      6      7      8      9     10     11 
598724  23941   5205   2125    521    159     78     74      9     22     12 
    14     17     20 
    14     17     20 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>MULTGEN)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1      2      3 
 26667 235977 325935  42342 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>ROOMS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1      2      3      4      5      6      7      8      9     10 
 26667   5045   6497  24120  64764 106700 116352  90387  74410  46023  31584 
    11     12     13     14     16     17 
 14897  10650   4450   1497   4600   2278 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>BEDROOMS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1      2      3      4      5      6      7 
 26667   6171  30572 130678 254820 139066  35198   7749 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>FAMSIZE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     1      2      3      4      5      6      7      8      9     10     11 
117220 173790 106581 118792  66955  28638  10458   4536   1935    960    462 
    12     13     14     15     20 
   288    143     98     45     20 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>FAMUNIT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     1      2      3      4      5      6      7      8      9     10     11 
617579  10356   2085    629    146     51     26     14      7      6      4 
    12     13     14     15     16     17     18     19     20 
     3      3      3      2      2      2      1      1      1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>NCHILD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1      2      3      4      5      6      7      8      9 
455516  81346  60564  24066   7061   1637    458    166     56     51 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>NCHLT5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1      2      3      4      5 
587378  32051  10371   1062     52      7 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>SEX)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     1      2 
308847 322074 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>MARST)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     1      2      3      4      5      6 
259436   9810   6975  52185  34556 267959 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>AGE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   0    1    2    3    4    5    6    7    8    9   10   11   12   13   14   15 
6164 6365 6490 6488 6750 6728 6755 7130 7312 7446 7536 7796 7724 7655 7781 7922 
  16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31 
8061 8184 8383 8014 7368 7052 7058 7270 7241 7513 7594 7700 7738 7798 7813 7597 
  32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47 
7793 7739 7889 7981 7660 7819 7553 7536 7676 7301 7308 7379 7422 7863 7959 7905 
  48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63 
7979 7998 8571 8441 8724 8876 9232 9509 9584 9516 9655 9579 9580 9428 9098 8745 
  64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79 
8766 8410 8095 7753 7540 6779 6595 6235 5827 5285 5031 4762 4539 3992 3902 3558 
  80   81   82   83   84   85   86   87   88   89   90   94 
3415 3155 2840 2586 2381 2209 2107 1853 1779 1584 1270 4949 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>RACE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     1      2      3      4      5      6      7      8      9 
496000  65329   1425   6165    801  22817  23984  13133   1267 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(data, COUPLETYPE, PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 x 5
  Response                    Frequency Percent `Valid Percent` `Cumulative Pe~`
  &lt;fct&gt;                           &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt;            &lt;dbl&gt;
1 N/A                           4404161  34.5            34.5               34.5
2 Opposite-sex husband/wife/~   7435716  58.2            58.2               92.7
3 Same-sex husband/wife/spou~     48693   0.381           0.381             93.1
4 Opposite-sex unmarried par~    843881   6.61            6.61              99.7
5 Same-sex unmarried partner~     38180   0.299           0.299            100  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ipums_var_desc(data, PWSTATE2)</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">PWSTATE2_clean =</span> <span class="fu">as_factor</span>(<span class="fu">lbl_na_if</span>(PWSTATE2, <span class="sc">~</span>.val <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>))))</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(PWSTATE2) <span class="sc">%&gt;%</span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">n=</span><span class="fu">sum</span>(PERWT)) <span class="sc">%&gt;%</span> <span class="co">#number of people that match that observation</span></span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span> n<span class="sc">/</span><span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span> </span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pct))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 59 x 3
          PWSTATE2       n      pct
         &lt;int+lbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
 1  0 [N/A]        6618007 0.518   
 2 17 [Illinois]   5933809 0.465   
 3 29 [Missouri]     87606 0.00686 
 4 18 [Indiana]      34843 0.00273 
 5 19 [Iowa]         32936 0.00258 
 6 55 [Wisconsin]    28751 0.00225 
 7 21 [Kentucky]      4788 0.000375
 8 26 [Michigan]      3046 0.000239
 9  6 [California]    2620 0.000205
10 48 [Texas]         2159 0.000169
# ... with 49 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCEARN))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  -7600       0    2294   28922   40484  943857 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 999999 is missing values and want positive income values</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(INCEARN<span class="sc">&gt;</span><span class="dv">0</span> <span class="sc">&amp;</span> INCWAGE <span class="sc">!=</span> <span class="dv">999999</span> <span class="sc">&amp;</span> INCWAGE <span class="sc">!=</span> <span class="dv">999998</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(AGE <span class="sc">&gt;</span> <span class="dv">25</span>)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 104,689 obs remaining if &gt;=0</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 65113 obs if &gt; 0</span></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 55332 observations if older than 25</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCEARN))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      1   22632   43164   61663   75000  943857 </code></pre>
</div>
</div>
</section>
<section id="descriptive-stats-after-dropping-missing-income-obs" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-stats-after-dropping-missing-income-obs">Descriptive stats after dropping missing income obs</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>EMPSTAT) <span class="co"># unweighted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     1      2      3 
262542   6434  13570 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">as_factor</span>(EMPSTAT)) <span class="sc">%&gt;%</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">n=</span><span class="fu">sum</span>(PERWT)) <span class="sc">%&gt;%</span> </span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span> n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 x 3
  `as_factor(EMPSTAT)`       n    pct
  &lt;fct&gt;                  &lt;dbl&gt;  &lt;dbl&gt;
1 Employed             5321354 0.936 
2 Unemployed            136278 0.0240
3 Not in labor force    229132 0.0403</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>LABFORCE) <span class="co"># unweighted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     1      2 
 13570 268976 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(<span class="fu">as_factor</span>(LABFORCE)) <span class="sc">%&gt;%</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">n=</span><span class="fu">sum</span>(PERWT)) <span class="sc">%&gt;%</span> </span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span> n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 x 3
  `as_factor(LABFORCE)`            n    pct
  &lt;fct&gt;                        &lt;dbl&gt;  &lt;dbl&gt;
1 No, not in the labor force  229132 0.0403
2 Yes, in the labor force    5457632 0.960 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>CLASSWKR)<span class="co"># unweighted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     1      2 
 28453 254093 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">as_factor</span>(CLASSWKR)) <span class="sc">%&gt;%</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">n=</span><span class="fu">sum</span>(PERWT)) <span class="sc">%&gt;%</span> </span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span> n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 x 3
  `as_factor(CLASSWKR)`       n    pct
  &lt;fct&gt;                   &lt;dbl&gt;  &lt;dbl&gt;
1 Self-employed          542103 0.0953
2 Works for wages       5144661 0.905 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TRANWORK) <span class="sc">%&gt;%</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">sum</span>(PERWT)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 x 2
                                                       TRANWORK       n
                                                      &lt;int+lbl&gt;   &lt;dbl&gt;
 1  0 [N/A]                                                      461812
 2 10 [Auto, truck, or van]                                     4249105
 3 20 [Motorcycle]                                                 3708
 4 31 [Bus]                                                      172195
 5 34 [Light rail, streetcar, or trolley (Carro público in PR)]    3409
 6 36 [Subway or elevated]                                       167020
 7 37 [Long-distance train or commuter train]                    136359
 8 38 [Taxicab]                                                   15951
 9 39 [Ferryboat]                                                   664
10 50 [Bicycle]                                                   30195
11 60 [Walked only]                                              122092
12 70 [Other]                                                     40135
13 80 [Worked at home]                                           284119</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(<span class="at">df =</span> data, <span class="at">variable =</span> LABFORCE, <span class="at">weight =</span> PERWT )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 x 5
  Response                   Frequency Percent `Valid Percent` `Cumulative Per~`
  &lt;fct&gt;                          &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt;             &lt;dbl&gt;
1 No, not in the labor force    229132    4.03            4.03              4.03
2 Yes, in the labor force      5457632   96.0            96.0             100   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(data, EMPSTAT, PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 x 5
  Response           Frequency Percent `Valid Percent` `Cumulative Percent`
  &lt;fct&gt;                  &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt;                &lt;dbl&gt;
1 Employed             5321354   93.6            93.6                  93.6
2 Unemployed            136278    2.40            2.40                 96.0
3 Not in labor force    229132    4.03            4.03                100  </code></pre>
</div>
</div>
<p><strong>Xiaoyan decile cutoffs:</strong></p>
<p>summarize incearn, detail<br>
*generate percentile and percent (equal frequency)<br>
pctile pct=incearn, nq(10) genp(percent)<br>
list percent pct in 1/10<br>
*how to incorporate svy weight in dividing the percentiles?<br>
*generate percentile range based on perentile calculation<br>
gen pctr=“(0,10%]” if incearn&lt;= 2024<br>
replace pctr=“(10%,20%]” if incearn&gt; 2024&amp;incearn&lt;=13558<br>
replace pctr=“(20%,30%]” if incearn&gt;13558&amp;incearn&lt;=23417<br>
replace pctr=“(30%,40%]” if incearn&gt;23417&amp;incearn&lt;=31961<br>
replace pctr=“(40%,50%]” if incearn&gt;31961&amp;incearn&lt;=40725<br>
replace pctr=“(50%,60%]” if incearn&gt;40725&amp;incearn&lt;=51104<br>
replace pctr=“(60%,70%]” if incearn&gt;51104&amp;incearn&lt;=63922<br>
replace pctr=“(70%,80%]” if incearn&gt;63922&amp;incearn&lt;=81000<br>
replace pctr=“(80%,90%]” if incearn&gt;81000&amp;incearn&lt;=111993<br>
replace pctr=“(90%,100%]” if incearn&gt;111993</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>telework<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"teleworkable2018onward.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
Rows: 1881 Columns: 9
-- Column specification
-------------------------------------------------------- Delimiter: "," chr
(2): occ_codes, Notes dbl (1): teleworkable lgl (6): ...3, ...4, ...5, ...6,
...7, ...8
i Use `spec()` to retrieve the full column specification for this data. i
Specify the column types or set `show_col_types = FALSE` to quiet this message.
* `` -&gt; `...3`
* `` -&gt; `...4`
* `` -&gt; `...5`
* `` -&gt; `...6`
* `` -&gt; `...7`
* `` -&gt; `...8`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>telework <span class="ot">&lt;-</span> telework <span class="sc">%&gt;%</span> </span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">CanWorkFromHome =</span> <span class="fu">case_when</span>(</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>  teleworkable <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"No WFH"</span>,</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>  teleworkable <span class="sc">&lt;</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Some WFH"</span>,</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>  teleworkable <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Can WFH"</span>,</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>  <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Check Me"</span>)</span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(telework<span class="sc">$</span>CanWorkFromHome)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Can WFH   No WFH Some WFH 
     480     1135      266 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># causes problems for any occupation code that has XX in it!! </span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="co">#data_labforce$OCCSOC_num &lt;- as.numeric(data_labforce$OCCSOC)</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>joined<span class="ot">&lt;-</span><span class="fu">left_join</span>(data, telework, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"OCCSOC"</span><span class="ot">=</span> <span class="st">"occ_codes"</span>))</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(joined<span class="sc">$</span>teleworkable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.0000  0.0000  0.4135  1.0000  1.0000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># teleworkable values are an average of occupations with same first 5 digits and first 4 digits.</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>joined <span class="sc">%&gt;%</span> <span class="fu">filter</span>(teleworkable<span class="sc">==</span><span class="st">"Some WFH"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 x 167
# ... with 167 variables: YEAR &lt;int&gt;, MULTYEAR &lt;dbl&gt;, SAMPLE &lt;int+lbl&gt;,
#   SERIAL &lt;dbl&gt;, CBSERIAL &lt;dbl&gt;, NUMPREC &lt;int&gt;, SUBSAMP &lt;int+lbl&gt;, HHWT &lt;dbl&gt;,
#   HHTYPE &lt;int+lbl&gt;, CBHHTYPE &lt;int+lbl&gt;, CLUSTER &lt;dbl&gt;, ADJUST &lt;dbl&gt;,
#   REGION &lt;int+lbl&gt;, STATEICP &lt;int+lbl&gt;, STATEFIP &lt;int+lbl&gt;,
#   COUNTYICP &lt;int+lbl&gt;, COUNTYFIP &lt;dbl+lbl&gt;, DENSITY &lt;dbl&gt;, METRO &lt;int+lbl&gt;,
#   CITY &lt;int+lbl&gt;, PUMA &lt;dbl+lbl&gt;, STRATA &lt;dbl&gt;, GQ &lt;int+lbl&gt;,
#   OWNERSHP &lt;int+lbl&gt;, OWNERSHPD &lt;int+lbl&gt;, MORTGAGE &lt;int+lbl&gt;, ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(srvyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'srvyr' was built under R version 4.0.5</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'srvyr'

The following object is masked from 'package:Hmisc':

    summarize

The following object is masked from 'package:stats':

    filter</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>dstrata <span class="ot">&lt;-</span> joined <span class="sc">%&gt;%</span> <span class="fu">as_survey</span>(<span class="at">strata =</span> STRATA , <span class="at">weights =</span> PERWT)</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>dstrata <span class="ot">&lt;-</span> dstrata <span class="sc">%&gt;%</span> </span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percentile =</span> <span class="fu">ntile</span>(INCEARN,<span class="dv">100</span>),</span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">decile =</span> <span class="fu">ntile</span>(INCEARN, <span class="dv">10</span>))</span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>         <span class="co">#,decile2 = survey_quantile(INCEARN, c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9)))</span></span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a>dstrata</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Stratified Independent Sampling design (with replacement)
Called via srvyr
Sampling variables:
 - ids: `1`
 - strata: STRATA
 - weights: PERWT
Data variables: YEAR (int), MULTYEAR (dbl), SAMPLE (int+lbl), SERIAL (dbl),
  CBSERIAL (dbl), NUMPREC (int), SUBSAMP (int+lbl), HHWT (dbl), HHTYPE
  (int+lbl), CBHHTYPE (int+lbl), CLUSTER (dbl), ADJUST (dbl), REGION (int+lbl),
  STATEICP (int+lbl), STATEFIP (int+lbl), COUNTYICP (int+lbl), COUNTYFIP
  (dbl+lbl), DENSITY (dbl), METRO (int+lbl), CITY (int+lbl), PUMA (dbl+lbl),
  STRATA (dbl), GQ (int+lbl), OWNERSHP (int+lbl), OWNERSHPD (int+lbl), MORTGAGE
  (int+lbl), OWNCOST (dbl+lbl), HHINCOME (dbl+lbl), VALUEH (int+lbl), ROOMS
  (int+lbl), BUILTYR2 (int+lbl), UNITSSTR (int+lbl), BEDROOMS (int+lbl),
  CINETHH (int+lbl), CILAPTOP (int+lbl), CISMRTPHN (int+lbl), CITABLET
  (int+lbl), CIOTHCOMP (int+lbl), CIDATAPLN (int+lbl), CIHISPEED (int+lbl),
  VEHICLES (int+lbl), COUPLETYPE (int+lbl), SSMC (int+lbl), NFAMS (int+lbl),
  NSUBFAM (int+lbl), NCOUPLES (int+lbl), NMOTHERS (int+lbl), NFATHERS
  (int+lbl), MULTGEN (int+lbl), MULTGEND (int+lbl), RESPMODE (int+lbl), PERNUM
  (dbl), PERWT (dbl), FAMUNIT (int+lbl), FAMSIZE (int+lbl), SUBFAM (int+lbl),
  SFTYPE (int+lbl), SFRELATE (int+lbl), SPRULE (int+lbl), NCHILD (int+lbl),
  NCHLT5 (int+lbl), RELATE (int+lbl), RELATED (int+lbl), SEX (int+lbl), AGE
  (int+lbl), MARST (int+lbl), MARRNO (int+lbl), MARRINYR (int+lbl), YRMARR
  (int+lbl), DIVINYR (int+lbl), WIDINYR (int+lbl), FERTYR (int+lbl), RACE
  (int+lbl), RACED (int+lbl), HISPAN (int+lbl), HISPAND (int+lbl), BPL
  (int+lbl), BPLD (int+lbl), ANCESTR1 (int+lbl), ANCESTR1D (int+lbl), ANCESTR2
  (int+lbl), ANCESTR2D (int+lbl), CITIZEN (int+lbl), YRNATUR (int+lbl), YRIMMIG
  (int+lbl), YRSUSA1 (int+lbl), LANGUAGE (int+lbl), LANGUAGED (int+lbl),
  SPEAKENG (int+lbl), HCOVANY (int+lbl), HCOVPRIV (int+lbl), HINSEMP (int+lbl),
  HINSPUR (int+lbl), HINSTRI (int+lbl), HCOVPUB (int+lbl), HINSCAID (int+lbl),
  HINSCARE (int+lbl), SCHOOL (int+lbl), EDUC (int+lbl), EDUCD (int+lbl),
  GRADEATT (int+lbl), GRADEATTD (int+lbl), SCHLTYPE (int+lbl), DEGFIELD
  (int+lbl), DEGFIELDD (int+lbl), DEGFIELD2 (int+lbl), DEGFIELD2D (int+lbl),
  EMPSTAT (int+lbl), EMPSTATD (int+lbl), LABFORCE (int+lbl), CLASSWKR
  (int+lbl), CLASSWKRD (int+lbl), OCC (int+lbl), OCC2010 (int+lbl), OCCSOC
  (chr), IND (int+lbl), WKSWORK1 (dbl+lbl), WKSWORK2 (int+lbl), UHRSWORK
  (int+lbl), WORKEDYR (int+lbl), INCTOT (dbl+lbl), FTOTINC (dbl+lbl), INCWAGE
  (dbl+lbl), INCWELFR (dbl+lbl), INCINVST (dbl+lbl), INCEARN (dbl+lbl), POVERTY
  (dbl+lbl), OCCSCORE (int+lbl), SEI (int), HWSEI (int+lbl), PRESGL (int+lbl),
  PRENT (int+lbl), MIGRATE1 (int+lbl), MIGRATE1D (int+lbl), MIGPLAC1 (int+lbl),
  MIGCOUNTY1 (dbl+lbl), MIGMET131 (int+lbl), MIGTYPE1 (int+lbl), MIGPUMA1
  (dbl+lbl), MOVEDIN (int+lbl), PWSTATE2 (int+lbl), PWCOUNTY (dbl+lbl), PWMET13
  (int+lbl), PWTYPE (int+lbl), PWPUMA00 (dbl+lbl), TRANWORK (int+lbl), TRANTIME
  (dbl+lbl), QOCC (int+lbl), QINCEARN (int+lbl), QINCBUS (int+lbl), QINCINVS
  (int+lbl), QINCOTHE (int+lbl), QINCRETI (int+lbl), QINCSS (int+lbl), QINCTOT
  (int+lbl), QINCWAGE (int+lbl), QINCWELF (int+lbl), PWSTATE2_clean (fct),
  teleworkable (dbl), ...3 (lgl), ...4 (lgl), ...5 (lgl), ...6 (lgl), ...7
  (lgl), ...8 (lgl), Notes (chr), CanWorkFromHome (chr), percentile (int),
  decile (int)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>summary <span class="ot">&lt;-</span> dstrata <span class="sc">%&gt;%</span> </span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(decile) <span class="sc">%&gt;%</span> </span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">min =</span> <span class="fu">min</span>(INCEARN),</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">max=</span><span class="fu">max</span>(INCEARN),</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_income =</span> <span class="fu">mean</span>(INCEARN),</span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">average_income =</span> <span class="fu">survey_mean</span>(INCEARN),</span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">pop_represented =</span> <span class="fu">sum</span>(PERWT),</span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">obs_count =</span> <span class="fu">n</span>())</span>
<span id="cb88-9"><a href="#cb88-9" aria-hidden="true" tabindex="-1"></a>summary </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 x 8
   decile                  min    max avg_income average_income average_income_~
    &lt;int&gt;            &lt;dbl+lbl&gt; &lt;dbl+&gt;      &lt;dbl&gt;          &lt;dbl&gt;            &lt;dbl&gt;
 1      1      1 [1 or break ~   9600      4487.          4573.             21.7
 2      2   9600                18776     14001.         14069.             20.9
 3      3  18776                26634     22820.         22789.             18.2
 4      4  26634                35000     30918.         30897.             17.9
 5      5  35000                43164     39403.         39384.             19.2
 6      6  43164                53955     48832.         48845.             22.9
 7      7  53955                66178     59868.         59856.             28.3
 8      8  66178                85000     75014.         75045.             38.7
 9      9  85000               117190     98582.         98594.             66.8
10     10 117190               943857    222709.        219125.            952. 
# ... with 2 more variables: pop_represented &lt;dbl&gt;, obs_count &lt;int&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>summary <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>decile, <span class="at">y=</span>average_income)) <span class="sc">+</span> <span class="fu">geom_col</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_2019ACS5year_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>dstrata <span class="sc">%&gt;%</span> </span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_data_frame</span>()<span class="sc">%&gt;%</span> </span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>decile)) <span class="sc">+</span> </span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">fill=</span>CanWorkFromHome), <span class="at">position=</span><span class="st">"dodge"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `as_data_frame()` was deprecated in tibble 2.0.0.
Please use `as_tibble()` instead.
The signature and semantics have changed, see `?as_tibble`.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="WorkFromHome_2019ACS5year_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>dstrata <span class="sc">%&gt;%</span> </span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_data_frame</span>()<span class="sc">%&gt;%</span> </span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>decile)) <span class="sc">+</span> </span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">y =</span> (..count..<span class="sc">/</span><span class="fu">sum</span>(..count..)), <span class="at">fill=</span>CanWorkFromHome), <span class="at">position=</span><span class="st">"dodge"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_2019ACS5year_files/figure-html/unnamed-chunk-4-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>dstrata <span class="sc">%&gt;%</span> </span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_data_frame</span>()<span class="sc">%&gt;%</span> </span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>decile, <span class="at">y =</span> (..count..)<span class="sc">/</span><span class="fu">sum</span>(..count..)<span class="sc">*</span><span class="dv">10</span>, <span class="at">fill =</span> CanWorkFromHome)) <span class="sc">+</span> </span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#geom_bar(aes(fill=CanWorkFromHome), position="dodge")+</span></span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">fill =</span> CanWorkFromHome), <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()<span class="sc">+</span>   <span class="co">#geom_text(aes(y = ((..count..)/sum(..count..)), label = scales::percent((..count..)/sum(..count..))), stat = "count", vjust = -0.25) +</span></span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a>     <span class="co"># scale_y_reverse(limits = rev)+</span></span>
<span id="cb94-9"><a href="#cb94-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-10"><a href="#cb94-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="st">"Bottom 10%"</span>, <span class="st">"20%"</span>, <span class="st">"30%"</span>, <span class="st">"40%"</span>, <span class="st">"50%"</span>, <span class="st">"60%"</span>, <span class="st">"70%"</span>, <span class="st">"80%"</span>, <span class="st">"90%"</span>, <span class="st">"Top 10%"</span>))<span class="sc">+</span> </span>
<span id="cb94-11"><a href="#cb94-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent)<span class="sc">+</span></span>
<span id="cb94-12"><a href="#cb94-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>) <span class="sc">+</span></span>
<span id="cb94-13"><a href="#cb94-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Able to work from home by income decile"</span>, </span>
<span id="cb94-14"><a href="#cb94-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Percent of Workers in each Income Decile"</span>,</span>
<span id="cb94-15"><a href="#cb94-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb94-16"><a href="#cb94-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"n = 282,546 in unweighted sample. Represents the 6.67 million in Illinois' workforce.</span></span>
<span id="cb94-17"><a href="#cb94-17" aria-hidden="true" tabindex="-1"></a><span class="st">       If 10% of workers in the 'Bottom 10%' income decile cannot work from home, </span></span>
<span id="cb94-18"><a href="#cb94-18" aria-hidden="true" tabindex="-1"></a><span class="st">       that is equal to 1% of the total population who can't work from home."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_2019ACS5year_files/figure-html/unnamed-chunk-4-4.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>dstrata <span class="sc">%&gt;%</span> </span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_data_frame</span>()<span class="sc">%&gt;%</span> </span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>decile, <span class="at">y =</span> (..count..<span class="sc">/</span><span class="fu">sum</span>(..count..)<span class="sc">*</span><span class="dv">10</span>))) <span class="sc">+</span> </span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">fill=</span>CanWorkFromHome), <span class="at">position=</span><span class="st">"dodge"</span>)<span class="sc">+</span></span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="st">"Bottom 10%"</span>, <span class="st">"20%"</span>, <span class="st">"30%"</span>, <span class="st">"40%"</span>, <span class="st">"50%"</span>, <span class="st">"60%"</span>, <span class="st">"70%"</span>, <span class="st">"80%"</span>, <span class="st">"90%"</span>, <span class="st">"Top 10%"</span>))<span class="sc">+</span> </span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>) <span class="sc">+</span></span>
<span id="cb95-8"><a href="#cb95-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent)<span class="sc">+</span></span>
<span id="cb95-9"><a href="#cb95-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Able to work from home by income decile"</span>, </span>
<span id="cb95-10"><a href="#cb95-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Percent of Workers in each Income Decile"</span>,</span>
<span id="cb95-11"><a href="#cb95-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"n = 282,546; Represents the 6.67 million in Illinois' workforce.</span></span>
<span id="cb95-12"><a href="#cb95-12" aria-hidden="true" tabindex="-1"></a><span class="st">       Data from 2019 5-Year ACS. </span></span>
<span id="cb95-13"><a href="#cb95-13" aria-hidden="true" tabindex="-1"></a><span class="st">       Occupation and ability to work from home values based on the work of D&amp;N"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_2019ACS5year_files/figure-html/unnamed-chunk-4-5.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCTOT))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  -3942   26471   47852   66744   79206 1230200 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCEARN))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      1   22632   43164   61663   75000  943857 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(data<span class="sc">$</span>INCTOT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$labels
                                   $9,900 (1980) 
                                           -9995 
                                 Net loss (1950) 
                                              -1 
                                            None 
                                               0 
1 or break even (2000, 2005-onward ACS and PRCS) 
                                               1 
                                             N/A 
                                         9999999 

$label
[1] "Total personal income"

$var_desc
[1] "INCTOT reports each respondent's total pre-tax personal income or losses from all sources for the previous year. The censuses collected information on income received from these sources during the previous calendar year; for the ACS and the PRCS, the reference period was the past 12 months. Amounts are expressed in contemporary dollars, and users studying change over time must adjust for inflation:\n\nUsers studying change over time must adjust for inflation. Consumer Price Index adjustment factors for the appropriate years can be found in the CPI99 variable.\n\nThe exception is the ACS/PRCS multi-year files, where all dollar amounts have been standardized to dollars as valued in the final year of data included in the file (e.g., 2007 dollars for the 2005-2007 3-year file). Additionally, more detail may be available than exists in the original ACS samples.\n\nUser Note: ACS respondents are surveyed throughout the year, and amounts do not reflect calendar year dollars. While the Census Bureau provides an adjustment factor (available in ADJUST), this is an imperfect solution. See the ACS income variables note for further details.\n\nFor a more complete discussion of the use of these factors to adjust for inflation, users may wish to see the IPUMS-CPS note on adjusting dollar amount variables for inflation."

$class
[1] "haven_labelled" "vctrs_vctr"     "double"        </code></pre>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(data<span class="sc">$</span>INCEARN)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$labels
                                   No earnings 
                                             0 
1 or break even (2000, 2005-2007 ACS and PRCS) 
                                             1 

$label
[1] "Total personal earned income"

$var_desc
[1] "INCEARN reports income earned from wages or a person's own business or farm for the previous year. The censuses collected information on income received from these sources during the previous calendar year; for the ACS and the PRCS, the reference period was the past 12 months. The value of INCEARN is the total for the IPUMS variables INCWAGE, INCBUS, and INCFARM (for 1990) and for INCWAGE and INCBUS00 (for the 2000 census, the ACS, and the PRCS). Note that these components of INCEARN are themselves already Top coded. See those variables for further discussion.  Because the universe for those variables is age 16+, all persons under age 16 have a value of 0 for INCEARN.\n\nAmounts are expressed in contemporary dollars, and users studying change over time must adjust for inflation (See INCTOT for Consumer Price Index adjustment factors).  The exception is the ACS/PRCS multi-year files, where all dollar amounts have been standardized to dollars as valued in the final year of data included in the file (e.g., 2007 dollars for the 2005-2007 3-year file). Additionally, more detail may be available than exists in the original ACS samples.  \n\nUser Note: ACS respondents are surveyed throughout the year, and amounts do not reflect calendar year dollars. While the Census Bureau provides an adjustment factor (available in ADJUST), this is an imperfect solution. See the ACS income variables note for further details."

$class
[1] "haven_labelled" "vctrs_vctr"     "double"        </code></pre>
</div>
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">incearn_decile =</span> <span class="fu">ntile</span>(INCEARN, <span class="dv">10</span>),</span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">percent_weight =</span> PERWT <span class="sc">/</span> <span class="fu">sum</span>(PERWT)<span class="sc">*</span><span class="dv">100</span>) <span class="sc">%&gt;%</span> <span class="co">#adds a variable to indicate which decile an observation falls within</span></span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">perwt_decile =</span> <span class="fu">ntile</span>(percent_weight, <span class="dv">10</span>))</span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-6"><a href="#cb104-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-7"><a href="#cb104-7" aria-hidden="true" tabindex="-1"></a>breaksummary <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb104-8"><a href="#cb104-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(perwt_decile)<span class="sc">%&gt;%</span></span>
<span id="cb104-9"><a href="#cb104-9" aria-hidden="true" tabindex="-1"></a>  <span class="co">#group_by(incearn_decile) %&gt;%</span></span>
<span id="cb104-10"><a href="#cb104-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">decile_min =</span> <span class="fu">min</span>(INCEARN),</span>
<span id="cb104-11"><a href="#cb104-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">decile_max =</span> <span class="fu">max</span>(INCEARN)</span>
<span id="cb104-12"><a href="#cb104-12" aria-hidden="true" tabindex="-1"></a>            ) </span>
<span id="cb104-13"><a href="#cb104-13" aria-hidden="true" tabindex="-1"></a>breaksummary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 x 3
   perwt_decile                                         decile_min decile_max
          &lt;int&gt;                                          &lt;dbl+lbl&gt;  &lt;dbl+lbl&gt;
 1            1 1 [1 or break even (2000, 2005-2007 ACS and PRCS)]     879471
 2            2 1 [1 or break even (2000, 2005-2007 ACS and PRCS)]     943857
 3            3 4                                                      943857
 4            4 1 [1 or break even (2000, 2005-2007 ACS and PRCS)]     933000
 5            5 4                                                      943857
 6            6 4                                                      943857
 7            7 1 [1 or break even (2000, 2005-2007 ACS and PRCS)]     943857
 8            8 1 [1 or break even (2000, 2005-2007 ACS and PRCS)]     943857
 9            9 1 [1 or break even (2000, 2005-2007 ACS and PRCS)]     943857
10           10 1 [1 or break even (2000, 2005-2007 ACS and PRCS)]     694000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>incearn_decile) <span class="co">#equal number of people, yay</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2     3     4     5     6     7     8     9    10 
28255 28255 28255 28255 28255 28255 28254 28254 28254 28254 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x=</span>INCEARN))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_2019ACS5year_files/figure-html/incearn-descripstats-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co">#   </span></span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="co"># data %&gt;% ggplot() +</span></span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   geom_col(aes(x=INCEARN, y=PERWT))+</span></span>
<span id="cb109-4"><a href="#cb109-4" aria-hidden="true" tabindex="-1"></a><span class="co">#   stat_bin(bins=10)#+ scale_x_continuous(labels = label_dollar())</span></span>
<span id="cb109-5"><a href="#cb109-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-6"><a href="#cb109-6" aria-hidden="true" tabindex="-1"></a><span class="co"># histogram of wages and salary income</span></span>
<span id="cb109-7"><a href="#cb109-7" aria-hidden="true" tabindex="-1"></a><span class="co">#  # unweighted</span></span>
<span id="cb109-8"><a href="#cb109-8" aria-hidden="true" tabindex="-1"></a><span class="co"># data %&gt;% ggplot(aes(x=INCEARN)) + </span></span>
<span id="cb109-9"><a href="#cb109-9" aria-hidden="true" tabindex="-1"></a><span class="co">#   stat_bin(bins=30)+ </span></span>
<span id="cb109-10"><a href="#cb109-10" aria-hidden="true" tabindex="-1"></a><span class="co">#   scale_x_continuous(labels = label_dollar())</span></span>
<span id="cb109-11"><a href="#cb109-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-12"><a href="#cb109-12" aria-hidden="true" tabindex="-1"></a><span class="co">#unweighted</span></span>
<span id="cb109-13"><a href="#cb109-13" aria-hidden="true" tabindex="-1"></a>h_unweighted<span class="ot">&lt;-</span><span class="fu">wtd.hist</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCEARN), <span class="at">breaks =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_2019ACS5year_files/figure-html/incearn-descripstats-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="co">#weighted</span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>h_weighted <span class="ot">&lt;-</span> <span class="fu">wtd.hist</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCEARN), <span class="at">breaks =</span> <span class="dv">10</span>,</span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">weight =</span> data<span class="sc">$</span>PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_2019ACS5year_files/figure-html/incearn-descripstats-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>h_unweighted</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$breaks
 [1] 0e+00 1e+05 2e+05 3e+05 4e+05 5e+05 6e+05 7e+05 8e+05 9e+05 1e+06

$counts
 [1] 242308  30601   4932    870    190   3476     80      4     36     49

$intensities
 [1] 8.575878e-06 1.083045e-06 1.745556e-07 3.079145e-08 6.724569e-09
 [6] 1.230242e-07 2.831397e-09 1.415699e-10 1.274129e-09 1.734231e-09

$density
 [1] 8.575878e-06 1.083045e-06 1.745556e-07 3.079145e-08 6.724569e-09
 [6] 1.230242e-07 2.831397e-09 1.415699e-10 1.274129e-09 1.734231e-09

$mids
 [1]  50000 150000 250000 350000 450000 550000 650000 750000 850000 950000

$xname
[1] "as.numeric(data$INCEARN)"

$equidist
[1] TRUE

attr(,"class")
[1] "histogram"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a>h_weighted</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$breaks
 [1] 0e+00 1e+05 2e+05 3e+05 4e+05 5e+05 6e+05 7e+05 8e+05 9e+05 1e+06

$counts
 [1] 4886204  615642   97864   16053    3556   64462    1511      53     550
[10]     869

$intensities
 [1] 8.592240e-06 1.082588e-06 1.720908e-07 2.822871e-08 6.253117e-09
 [6] 1.133544e-07 2.657047e-09 9.319887e-11 9.671581e-10 1.528110e-09

$density
 [1] 8.592240e-06 1.082588e-06 1.720908e-07 2.822871e-08 6.253117e-09
 [6] 1.133544e-07 2.657047e-09 9.319887e-11 9.671581e-10 1.528110e-09

$mids
 [1]  50000 150000 250000 350000 450000 550000 650000 750000 850000 950000

$xname
[1] "as.numeric(data$INCEARN)"

$equidist
[1] TRUE

attr(,"class")
[1] "histogram"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>h_unweighted<span class="sc">$</span>breaks</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0e+00 1e+05 2e+05 3e+05 4e+05 5e+05 6e+05 7e+05 8e+05 9e+05 1e+06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>h_weighted<span class="sc">$</span>breaks</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0e+00 1e+05 2e+05 3e+05 4e+05 5e+05 6e+05 7e+05 8e+05 9e+05 1e+06</code></pre>
</div>
</div>
<section id="adding-occupation-codes" class="level4">
<h4 class="anchored" data-anchor-id="adding-occupation-codes">Adding Occupation codes</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="co"># noOCCSOC&lt;- data %&gt;% </span></span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   filter(OCCSOC == 0) #98205 with occsoc=0</span></span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb119-4"><a href="#cb119-4" aria-hidden="true" tabindex="-1"></a><span class="co"># table(noOCCSOC$EMPSTAT)</span></span>
<span id="cb119-5"><a href="#cb119-5" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb119-6"><a href="#cb119-6" aria-hidden="true" tabindex="-1"></a><span class="co"># before filtering out the incwage and inctot variables for 0's and negatives, </span></span>
<span id="cb119-7"><a href="#cb119-7" aria-hidden="true" tabindex="-1"></a><span class="co"># #98% of the people without Occupation codes are not in the labor force. Makes sense</span></span>
<span id="cb119-8"><a href="#cb119-8" aria-hidden="true" tabindex="-1"></a><span class="co"># all observations have occsoc codes after filtering for INCWAGE and INCTOT and previous steps</span></span>
<span id="cb119-9"><a href="#cb119-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-10"><a href="#cb119-10" aria-hidden="true" tabindex="-1"></a>data_labforce <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(OCCSOC <span class="sc">!=</span> <span class="dv">0</span>) <span class="co"># none are dropped</span></span>
<span id="cb119-11"><a href="#cb119-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-12"><a href="#cb119-12" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(<span class="at">df =</span> data_labforce, <span class="at">variable =</span> EMPSTAT, <span class="at">weight =</span> PERWT )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 x 5
  Response           Frequency Percent `Valid Percent` `Cumulative Percent`
  &lt;fct&gt;                  &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt;                &lt;dbl&gt;
1 Employed             5321354   93.6            93.6                  93.6
2 Unemployed            136278    2.40            2.40                 96.0
3 Not in labor force    229132    4.03            4.03                100  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(data_labforce<span class="sc">$</span>PERWT) <span class="co"># 6.67 million people</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5686764</code></pre>
</div>
</div>
<p>Look at decile breaks for INCEARN:</p>
<p><em>These are different than Xiaoyans</em>? Double check??</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a>income_deciles <span class="ot">&lt;-</span> data_labforce <span class="sc">%&gt;%</span> </span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">ntile</span>(INCWAGE, <span class="dv">10</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb123-3"><a href="#cb123-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">mean_inc =</span> <span class="fu">mean</span>(INCWAGE)) </span>
<span id="cb123-4"><a href="#cb123-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-5"><a href="#cb123-5" aria-hidden="true" tabindex="-1"></a>income_deciles</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 x 2
   `ntile(INCWAGE, 10)` mean_inc
                  &lt;int&gt;    &lt;dbl&gt;
 1                    1    1182.
 2                    2   10286.
 3                    3   20195.
 4                    4   28932.
 5                    5   37609.
 6                    6   47109.
 7                    7   58185.
 8                    8   73028.
 9                    9   96057.
10                   10  211093.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a>data_labforce <span class="sc">%&gt;%</span> </span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">ntile</span>(INCWAGE,<span class="dv">10</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb125-3"><a href="#cb125-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">mean_inc =</span> <span class="fu">mean</span>(<span class="fu">as.numeric</span>(INCWAGE)) )<span class="sc">%&gt;%</span></span>
<span id="cb125-4"><a href="#cb125-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb125-5"><a href="#cb125-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">INCWAGE_decile=</span><span class="st">'ntile(INCWAGE,10)'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb125-6"><a href="#cb125-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">ntile</span>(INCWAGE_decile,<span class="dv">10</span>), <span class="at">y=</span>mean_inc)) <span class="sc">+</span> </span>
<span id="cb125-7"><a href="#cb125-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb125-8"><a href="#cb125-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Income decile"</span>, <span class="at">y=</span><span class="st">"Mean Income"</span>, <span class="at">title =</span> <span class="st">"Average Income for each Income Decile."</span>) <span class="sc">+</span></span>
<span id="cb125-9"><a href="#cb125-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_2019ACS5year_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>teleworkable2010.csv has the 6digit OCCSOC codes. I also added the 5 digit broader version that ends with a 0 in the 6th digit to increase the chances of matching. Updated teleworkable2010.csv again with 4digitXX codes and 5digitXcodes to increase matching. Final version with even more options was named teleworkable2018onward.csv</em></p>
<p>teleworkable2018onward.csv has all codes (2010, 2019 transition, &amp; new 2018 codes)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="co">#telework csv uses data from Dingle and Nieman</span></span>
<span id="cb126-2"><a href="#cb126-2" aria-hidden="true" tabindex="-1"></a><span class="co"># https://github.com/jdingel/DingelNeiman-workathome/blob/master/occ_manual_scores/input/Teleworkable_BNJDopinion.csv</span></span>
<span id="cb126-3"><a href="#cb126-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-4"><a href="#cb126-4" aria-hidden="true" tabindex="-1"></a>telework<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"teleworkable.csv"</span>)</span>
<span id="cb126-5"><a href="#cb126-5" aria-hidden="true" tabindex="-1"></a><span class="co">#telework&lt;- read_csv("teleworkable2018onward.csv")</span></span>
<span id="cb126-6"><a href="#cb126-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-7"><a href="#cb126-7" aria-hidden="true" tabindex="-1"></a>telework <span class="ot">&lt;-</span> telework <span class="sc">%&gt;%</span> </span>
<span id="cb126-8"><a href="#cb126-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">CanWorkFromHome =</span> <span class="fu">case_when</span>(</span>
<span id="cb126-9"><a href="#cb126-9" aria-hidden="true" tabindex="-1"></a>  teleworkable <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"No WFH"</span>,</span>
<span id="cb126-10"><a href="#cb126-10" aria-hidden="true" tabindex="-1"></a>  teleworkable <span class="sc">&lt;</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Some WFH"</span>,</span>
<span id="cb126-11"><a href="#cb126-11" aria-hidden="true" tabindex="-1"></a>  teleworkable <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Can WFH"</span>,</span>
<span id="cb126-12"><a href="#cb126-12" aria-hidden="true" tabindex="-1"></a>  <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Check Me"</span>)</span>
<span id="cb126-13"><a href="#cb126-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb126-14"><a href="#cb126-14" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(telework<span class="sc">$</span>CanWorkFromHome)</span>
<span id="cb126-15"><a href="#cb126-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb126-16"><a href="#cb126-16" aria-hidden="true" tabindex="-1"></a><span class="co"># causes problems for any occupation code that has XX in it!! </span></span>
<span id="cb126-17"><a href="#cb126-17" aria-hidden="true" tabindex="-1"></a><span class="co">#data_labforce$OCCSOC_num &lt;- as.numeric(data_labforce$OCCSOC)</span></span>
<span id="cb126-18"><a href="#cb126-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-19"><a href="#cb126-19" aria-hidden="true" tabindex="-1"></a>innerjoined<span class="ot">&lt;-</span><span class="fu">inner_join</span>(data_labforce, telework, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"OCCSOC"</span><span class="ot">=</span> <span class="st">"onetsoc_6digits"</span>))</span>
<span id="cb126-20"><a href="#cb126-20" aria-hidden="true" tabindex="-1"></a><span class="co"># 65113 obs in innerjoin</span></span>
<span id="cb126-21"><a href="#cb126-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-22"><a href="#cb126-22" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(innerjoined<span class="sc">$</span>teleworkable)</span>
<span id="cb126-23"><a href="#cb126-23" aria-hidden="true" tabindex="-1"></a><span class="co"># teleworkable values are an average of occupations with same first 5 digits and first 4 digits. </span></span>
<span id="cb126-24"><a href="#cb126-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-25"><a href="#cb126-25" aria-hidden="true" tabindex="-1"></a>innerjoined <span class="sc">%&gt;%</span> <span class="fu">count</span>()</span>
<span id="cb126-26"><a href="#cb126-26" aria-hidden="true" tabindex="-1"></a>innerjoined <span class="sc">%&gt;%</span> <span class="fu">count</span>()</span>
<span id="cb126-27"><a href="#cb126-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-28"><a href="#cb126-28" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(innerjoined, <span class="fu">aes</span>(INCEARN))</span>
<span id="cb126-29"><a href="#cb126-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-30"><a href="#cb126-30" aria-hidden="true" tabindex="-1"></a>g <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="at">width=</span><span class="dv">10000</span>)</span>
<span id="cb126-31"><a href="#cb126-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-32"><a href="#cb126-32" aria-hidden="true" tabindex="-1"></a>g <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">weight =</span> PERWT),<span class="at">width=</span><span class="dv">10000</span>)</span>
<span id="cb126-33"><a href="#cb126-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-34"><a href="#cb126-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-35"><a href="#cb126-35" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(innerjoined<span class="sc">$</span>PERWT)</span>
<span id="cb126-36"><a href="#cb126-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-37"><a href="#cb126-37" aria-hidden="true" tabindex="-1"></a><span class="co"># innerjoined  %&gt;% ggplot() +</span></span>
<span id="cb126-38"><a href="#cb126-38" aria-hidden="true" tabindex="-1"></a><span class="co">#   geom_bar(aes(ntile(INCEARN,10)), weight=PERWT, bins = 10)+</span></span>
<span id="cb126-39"><a href="#cb126-39" aria-hidden="true" tabindex="-1"></a><span class="co">#   labs(title = "Unweighted Income Distribution")</span></span>
<span id="cb126-40"><a href="#cb126-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-41"><a href="#cb126-41" aria-hidden="true" tabindex="-1"></a><span class="co"># ggplot(innerjoined) +</span></span>
<span id="cb126-42"><a href="#cb126-42" aria-hidden="true" tabindex="-1"></a><span class="co">#   geom_bar(aes(x=ntile(INCEARN,10), weight = PERWT), bins = 10, stat = "identity")+</span></span>
<span id="cb126-43"><a href="#cb126-43" aria-hidden="true" tabindex="-1"></a><span class="co">#   labs(title = "Unweighted Income Distribution")</span></span>
<span id="cb126-44"><a href="#cb126-44" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb126-45"><a href="#cb126-45" aria-hidden="true" tabindex="-1"></a><span class="co"># # didn't change =[ </span></span>
<span id="cb126-46"><a href="#cb126-46" aria-hidden="true" tabindex="-1"></a><span class="co"># ggplot(innerjoined, aes(INCEARN)) +</span></span>
<span id="cb126-47"><a href="#cb126-47" aria-hidden="true" tabindex="-1"></a><span class="co">#   geom_histogram(aes(weight =  data_labforce$PERWT), bins = 100, stat = "freq")+</span></span>
<span id="cb126-48"><a href="#cb126-48" aria-hidden="true" tabindex="-1"></a><span class="co">#   labs(title = "Weighted Income Distribution")</span></span>
<span id="cb126-49"><a href="#cb126-49" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb126-50"><a href="#cb126-50" aria-hidden="true" tabindex="-1"></a><span class="co"># ggplot(innerjoined, aes(INCEARN)) +</span></span>
<span id="cb126-51"><a href="#cb126-51" aria-hidden="true" tabindex="-1"></a><span class="co">#   geom_histogram(aes(), bins = 10)+</span></span>
<span id="cb126-52"><a href="#cb126-52" aria-hidden="true" tabindex="-1"></a><span class="co">#   labs(title = "Unweighted Income Distribution")</span></span>
<span id="cb126-53"><a href="#cb126-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-54"><a href="#cb126-54" aria-hidden="true" tabindex="-1"></a><span class="co"># didn't change =[ </span></span>
<span id="cb126-55"><a href="#cb126-55" aria-hidden="true" tabindex="-1"></a>h_w <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(innerjoined, <span class="fu">aes</span>(INCEARN)) <span class="sc">+</span></span>
<span id="cb126-56"><a href="#cb126-56" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">weight =</span>  data_labforce<span class="sc">$</span>PERWT), <span class="at">bins =</span> <span class="dv">10</span>)<span class="sc">+</span></span>
<span id="cb126-57"><a href="#cb126-57" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Weighted Income Distribution"</span>)</span>
<span id="cb126-58"><a href="#cb126-58" aria-hidden="true" tabindex="-1"></a>h_w<span class="sc">$</span>breaks</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>innerjoined <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">ntile</span>(INCWAGE,<span class="dv">10</span>), <span class="at">y=</span>PERWT, <span class="at">fill =</span> CanWorkFromHome), <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Ability to Work from Home based on Occupation Characteristics"</span>, <span class="at">x =</span> <span class="st">"Income decile"</span>, <span class="at">caption=</span> <span class="st">"Based on D&amp;N teleworkable categorization and expanded for new 2018 SOC OCC codes. </span></span>
<span id="cb127-4"><a href="#cb127-4" aria-hidden="true" tabindex="-1"></a><span class="st">       Sample: 2021 ACS 1-Year, 65,113 observations </span></span>
<span id="cb127-5"><a href="#cb127-5" aria-hidden="true" tabindex="-1"></a><span class="st">       representing 6.67 million people in Illinois' workforce."</span>)</span>
<span id="cb127-6"><a href="#cb127-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-7"><a href="#cb127-7" aria-hidden="true" tabindex="-1"></a>innerjoined <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb127-8"><a href="#cb127-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">ntile</span>(INCWAGE,<span class="dv">10</span>), <span class="at">fill =</span> CanWorkFromHome), <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb127-9"><a href="#cb127-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Ability to Work from Home based on Occupation Characteristics"</span>, <span class="at">x =</span> <span class="st">"Income decile"</span>, <span class="at">caption=</span> <span class="st">"Based on D&amp;N teleworkable categorization and expanded for new 2018 SOC OCC codes. </span></span>
<span id="cb127-10"><a href="#cb127-10" aria-hidden="true" tabindex="-1"></a><span class="st">       Sample: 2021 ACS 1-Year, 65,113 observations </span></span>
<span id="cb127-11"><a href="#cb127-11" aria-hidden="true" tabindex="-1"></a><span class="st">       representing 6.67 million people in Illinois' workforce."</span>)</span>
<span id="cb127-12"><a href="#cb127-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-13"><a href="#cb127-13" aria-hidden="true" tabindex="-1"></a>leftjoined<span class="ot">&lt;-</span><span class="fu">left_join</span>(data_labforce, telework, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"OCCSOC"</span><span class="ot">=</span> <span class="st">"occ_codes"</span>))</span>
<span id="cb127-14"><a href="#cb127-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(innerjoined<span class="sc">$</span>teleworkable)</span>
<span id="cb127-15"><a href="#cb127-15" aria-hidden="true" tabindex="-1"></a><span class="co">#innerjoined&lt;-inner_join(data_labforce, telework, by = c("OCCSOC_num"= "BroadGroupCode"))</span></span>
<span id="cb127-16"><a href="#cb127-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-17"><a href="#cb127-17" aria-hidden="true" tabindex="-1"></a><span class="co">#leftjoined&lt;-left_join(data_labforce, telework, by = c("OCCSOC_num"= "BroadGroupCode"))</span></span>
<span id="cb127-18"><a href="#cb127-18" aria-hidden="true" tabindex="-1"></a><span class="co"># keeps all observations in data 2 even if they don't match</span></span>
<span id="cb127-19"><a href="#cb127-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-20"><a href="#cb127-20" aria-hidden="true" tabindex="-1"></a><span class="co">#antijoin &lt;-anti_join(data_labforce, telework, by = c("OCCSOC_num"= "onetsoc_6digits"))</span></span>
<span id="cb127-21"><a href="#cb127-21" aria-hidden="true" tabindex="-1"></a><span class="co"># 158525. Many were aggregated to 5digits with 6digit as 0.</span></span>
<span id="cb127-22"><a href="#cb127-22" aria-hidden="true" tabindex="-1"></a><span class="co"># 91403 obs after updating teleworkable file to 5digits with 6digit as 0</span></span>
<span id="cb127-23"><a href="#cb127-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-24"><a href="#cb127-24" aria-hidden="true" tabindex="-1"></a><span class="co">#couldnt use _num version due to XX in values.</span></span>
<span id="cb127-25"><a href="#cb127-25" aria-hidden="true" tabindex="-1"></a><span class="co">#antijoin &lt;-anti_join(data_labforce, telework, by = c("OCCSOC"= "onetsoc_6digits"))</span></span>
<span id="cb127-26"><a href="#cb127-26" aria-hidden="true" tabindex="-1"></a><span class="co"># 50,659 obs after adding 5digitsX and 4digitsXX and 5digits with sixth as 0 to csv file</span></span>
<span id="cb127-27"><a href="#cb127-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-28"><a href="#cb127-28" aria-hidden="true" tabindex="-1"></a><span class="co">#unique(antijoin$OCCSOC) #121 unique codes did not match.</span></span>
<span id="cb127-29"><a href="#cb127-29" aria-hidden="true" tabindex="-1"></a><span class="co"># down to 67 after adding 5digitsX and 4digitsXX and 5digits with sixth as 0 to csv file</span></span>
<span id="cb127-30"><a href="#cb127-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-31"><a href="#cb127-31" aria-hidden="true" tabindex="-1"></a><span class="co">#joined &lt;- joined %&gt;% mutate(occsoc5digits = substr(OCCSOC,1,5))</span></span>
<span id="cb127-32"><a href="#cb127-32" aria-hidden="true" tabindex="-1"></a><span class="co">#table(joined$occsoc5digits)</span></span>
<span id="cb127-33"><a href="#cb127-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-34"><a href="#cb127-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-35"><a href="#cb127-35" aria-hidden="true" tabindex="-1"></a><span class="co">#table(joined$Teleworkable)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Drops a lot of observations using inner join (equivalent to Stata merge==1) this join. 67,299 observations match SOC codes. I think so many do not match due to the use of 2010 , 2019 transition, and 2018 SOC OCC codes. To check this, I try joining the ACS data with the updated 2018 codes. (Authors used 2010 codes in original paper but they did do one for states that appear to have the 2018 codes?) Double check this.</p>
<ul>
<li>Using the 2021 ACS 1-year Sample should use only 2018 OCC codes since that data should be collected after they transitioned their occupation codes.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a>occ_2018 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"2018OCCcodes.csv"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">soc2018_6figs =</span> <span class="fu">as.character</span>(soc2018_6figs))</span>
<span id="cb128-3"><a href="#cb128-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-4"><a href="#cb128-4" aria-hidden="true" tabindex="-1"></a>joined2018codes <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(data_labforce, occ_2018, </span>
<span id="cb128-5"><a href="#cb128-5" aria-hidden="true" tabindex="-1"></a>                              <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"OCCSOC"</span> <span class="ot">=</span> <span class="st">"soc2018_6figs"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb128-6"><a href="#cb128-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">occsoc5digits =</span> <span class="fu">substr</span>(OCCSOC,<span class="dv">1</span>,<span class="dv">5</span>))</span>
<span id="cb128-7"><a href="#cb128-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 59,626 observations</span></span>
<span id="cb128-8"><a href="#cb128-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-9"><a href="#cb128-9" aria-hidden="true" tabindex="-1"></a>antijoin <span class="ot">&lt;-</span> <span class="fu">anti_join</span>(data_labforce, occ_2018, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"OCCSOC"</span> <span class="ot">=</span> <span class="st">"soc2018_6figs"</span>))</span>
<span id="cb128-10"><a href="#cb128-10" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(antijoin<span class="sc">$</span>OCCSOC)</span>
<span id="cb128-11"><a href="#cb128-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-12"><a href="#cb128-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-13"><a href="#cb128-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-14"><a href="#cb128-14" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(joined2018codes<span class="sc">$</span>occsoc5digits)</span>
<span id="cb128-15"><a href="#cb128-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-16"><a href="#cb128-16" aria-hidden="true" tabindex="-1"></a>occ_2018 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"teleworkable2018onwards.csv"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb128-17"><a href="#cb128-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">onetsoc_6digits =</span> <span class="fu">as.character</span>(onetsoc_6digits))</span>
<span id="cb128-18"><a href="#cb128-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-19"><a href="#cb128-19" aria-hidden="true" tabindex="-1"></a>joined2018codes <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(data_labforce, occ_2018, </span>
<span id="cb128-20"><a href="#cb128-20" aria-hidden="true" tabindex="-1"></a>                              <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"OCCSOC"</span> <span class="ot">=</span> <span class="st">"onetsoc_6digits"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb128-21"><a href="#cb128-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">occsoc5digits =</span> <span class="fu">substr</span>(OCCSOC,<span class="dv">1</span>,<span class="dv">5</span>))</span>
<span id="cb128-22"><a href="#cb128-22" aria-hidden="true" tabindex="-1"></a><span class="co"># 65113 observations? </span></span>
<span id="cb128-23"><a href="#cb128-23" aria-hidden="true" tabindex="-1"></a><span class="co"># I think they all matched? Now I just need to finish creating the average teleworkable variable</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>joining the remaining observations from 2021 1-year ACS data to the 2018 OCC codes results in 65113 matches</p>
<p><strong>OCC2010 variable labels:</strong></p>
<p>From DDI on IPUMS download: https://live.usa.datadownload.ipums.org/web/extracts/usa/1985137/usa_00006.xml#OCC</p>
<p>Management, Business, Science, and Arts = 10-430<br>
Business Operations Specialists = 500-730<br>
Financial Specialists = 800-950<br>
Computer and Mathematical = 1000-1240<br>
Architecture and Engineering = 1300-1540<br>
Technicians = 1550-1560<br>
Life, Physical, and Social Science = 1600-1980<br>
Community and Social Services = 2000-2060<br>
Legal = 2100-2150<br>
Education, Training, and Library = 2200-2550<br>
Arts, Design, Entertainment, Sports, and Media = 2600-2920<br>
Healthcare Practitioners and Technicians = 3000-3540<br>
Healthcare Support = 3600-3650<br>
Protective Service = 3700-3950<br>
Food Preparation and Serving = 4000-4150<br>
Building and Grounds Cleaning and Maintenance = 4200-4250<br>
Personal Care and Service = 4300-4650<br>
Sales and Related = 4700-4965<br>
Office and Administrative Support = 5000-5940<br>
Farming, Fishing, and Forestry = 6005-6130<br>
Construction = 6200-6765<br>
Extraction = 6800-6940<br>
Installation, Maintenance, and Repair = 7000-7630<br>
Production = 7700-8965<br>
Transportation and Material Moving = 9000-9750<br>
Military Specific = 9800-9830<br>
Unemployed (no occupation for 5+ years) or Never Worked = 9920<br>
</p>
</section>
</section>
</section>
<section id="pumas-and-shapefiles" class="level2">
<h2 class="anchored" data-anchor-id="pumas-and-shapefiles">PUMAs and Shapefiles</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="co"># PUMA shapefiles</span></span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a>pumasIL <span class="ot">&lt;-</span> <span class="fu">pumas</span>(<span class="st">"IL"</span>, <span class="at">cb=</span>T, <span class="at">year=</span><span class="dv">2019</span>)</span>
<span id="cb129-3"><a href="#cb129-3" aria-hidden="true" tabindex="-1"></a><span class="co">#county shapefiles</span></span>
<span id="cb129-4"><a href="#cb129-4" aria-hidden="true" tabindex="-1"></a>countyIL <span class="ot">&lt;-</span> <span class="fu">counties</span>(<span class="st">"IL"</span>, <span class="at">cb=</span>T, <span class="at">year=</span><span class="dv">2019</span>)</span>
<span id="cb129-5"><a href="#cb129-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-6"><a href="#cb129-6" aria-hidden="true" tabindex="-1"></a><span class="co">#pumasdf &lt;- fortify(pumasIL, region = 'PUMACE10')</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a>pums_weighted <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(PUMA, COUNTYFIP) <span class="sc">%&gt;%</span> </span>
<span id="cb130-3"><a href="#cb130-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">weighted =</span> <span class="fu">sum</span>(PERWT)) <span class="sc">%&gt;%</span>  <span class="co">#number of people the sample represents</span></span>
<span id="cb130-4"><a href="#cb130-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">PUMA =</span> <span class="fu">str_pad</span>(PUMA, <span class="dv">5</span>, <span class="at">pad=</span><span class="st">"0"</span>),</span>
<span id="cb130-5"><a href="#cb130-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">countyFIP =</span> <span class="fu">str_pad</span>(COUNTYFIP, <span class="dv">3</span>, <span class="at">pad =</span> <span class="st">"0"</span>))</span>
<span id="cb130-6"><a href="#cb130-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-7"><a href="#cb130-7" aria-hidden="true" tabindex="-1"></a>pums_unweight <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb130-8"><a href="#cb130-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(PUMA, COUNTYFIP) <span class="sc">%&gt;%</span> </span>
<span id="cb130-9"><a href="#cb130-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">unweight =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="co">#unweighted number of observations</span></span>
<span id="cb130-10"><a href="#cb130-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">PUMA =</span> <span class="fu">str_pad</span>(PUMA, <span class="dv">5</span>, <span class="at">pad=</span><span class="st">"0"</span>),</span>
<span id="cb130-11"><a href="#cb130-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">countyFIP =</span> <span class="fu">str_pad</span>(COUNTYFIP, <span class="dv">3</span>, <span class="at">pad =</span> <span class="st">"0"</span>))</span>
<span id="cb130-12"><a href="#cb130-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-13"><a href="#cb130-13" aria-hidden="true" tabindex="-1"></a>plotweighted <span class="ot">&lt;-</span> pumasIL <span class="sc">%&gt;%</span> </span>
<span id="cb130-14"><a href="#cb130-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(pums_weighted, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"PUMACE10"</span> <span class="ot">=</span> <span class="st">"PUMA"</span>))</span>
<span id="cb130-15"><a href="#cb130-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-16"><a href="#cb130-16" aria-hidden="true" tabindex="-1"></a>plotunweight <span class="ot">&lt;-</span> pumasIL <span class="sc">%&gt;%</span> </span>
<span id="cb130-17"><a href="#cb130-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(pums_unweight, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"PUMACE10"</span> <span class="ot">=</span> <span class="st">"PUMA"</span>))</span>
<span id="cb130-18"><a href="#cb130-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-19"><a href="#cb130-19" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plotweighted[<span class="st">"weighted"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_2019ACS5year_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plotunweight[<span class="st">"unweight"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_2019ACS5year_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a>FIPweighted <span class="ot">&lt;-</span> countyIL <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(pums_weighted, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"COUNTYFP"</span> <span class="ot">=</span> <span class="st">"countyFIP"</span>))</span>
<span id="cb132-2"><a href="#cb132-2" aria-hidden="true" tabindex="-1"></a>FIPunweight <span class="ot">&lt;-</span> countyIL <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(pums_unweight, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"COUNTYFP"</span> <span class="ot">=</span> <span class="st">"countyFIP"</span>))</span>
<span id="cb132-3"><a href="#cb132-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(FIPweighted[<span class="st">"weighted"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_2019ACS5year_files/figure-html/unnamed-chunk-10-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(FIPunweight[<span class="st">"unweight"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_2019ACS5year_files/figure-html/unnamed-chunk-10-4.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(countyIL[<span class="st">"COUNTYFP"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WorkFromHome_2019ACS5year_files/figure-html/unnamed-chunk-10-5.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="pumas-vs-commzone-vs-counties" class="level4">
<h4 class="anchored" data-anchor-id="pumas-vs-commzone-vs-counties">PUMAS vs COMMZONE vs COUNTIES</h4>
<p><a href="https://eig.org/the-uneven-geography-of-remote-work/">Link from Francis on COMZONE variable</a> (Commuter Zones)</p>
<p><a href="https://univofillinois.maps.arcgis.com/apps/mapviewer/index.html?layers=71eb4ef236ca42c4b577a0a105e790e2">Interactive ESRI Map of all PUMA outlines</a></p>
<p><a href="https://atcoordinates.info/2019/05/13/calculating-mean-income-for-groups-of-geographies-with-census-acs-data/">Article on calculating mean income for groups of geographies with ACS data</a></p>
</section>
</section>
<section id="acs-2019-5-year-data---original-download" class="level2">
<h2 class="anchored" data-anchor-id="acs-2019-5-year-data---original-download">ACS 2019 5-year Data - Original Download</h2>
<p>First download that had 2019 and 2021 data together. Then filtered for just 2019. Will probably delete. If anything, the 2019 data needs to be redownloaded if we do use it to add a few variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a>ddi <span class="ot">&lt;-</span> <span class="fu">read_ipums_ddi</span>(<span class="st">"usa_00006.xml"</span>)</span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_ipums_micro</span>(ddi)</span>
<span id="cb135-3"><a href="#cb135-3" aria-hidden="true" tabindex="-1"></a>data_labforce019 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(STATEFIP, REGION)) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(YEAR <span class="sc">==</span> <span class="st">"2019"</span>)</span>
<span id="cb135-4"><a href="#cb135-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(data)</span>
<span id="cb135-5"><a href="#cb135-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 621,164 observations for ACS2021 5-Year sample</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="descriptive-statistics" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-statistics">Descriptive Statistics</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data_labforce019</span>
<span id="cb136-2"><a href="#cb136-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(data_labforce019)</span>
<span id="cb136-3"><a href="#cb136-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>EMPSTAT) <span class="co"># unweighted</span></span>
<span id="cb136-4"><a href="#cb136-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>LABFORCE) <span class="co"># unweighted</span></span>
<span id="cb136-5"><a href="#cb136-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb136-6"><a href="#cb136-6" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>CLASSWKR)<span class="co"># unweighted</span></span>
<span id="cb136-7"><a href="#cb136-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb136-8"><a href="#cb136-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb136-9"><a href="#cb136-9" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(<span class="at">df =</span> data, <span class="at">variable =</span> LABFORCE, <span class="at">weight =</span> PERWT )</span>
<span id="cb136-10"><a href="#cb136-10" aria-hidden="true" tabindex="-1"></a><span class="fu">crosstab</span>(data, <span class="at">x=</span>MULTYEAR, <span class="at">y =</span> LABFORCE, <span class="at">weight =</span> PERWT)</span>
<span id="cb136-11"><a href="#cb136-11" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(data, EMPSTAT, PERWT)</span>
<span id="cb136-12"><a href="#cb136-12" aria-hidden="true" tabindex="-1"></a><span class="fu">crosstab</span>(data, <span class="at">x=</span>MULTYEAR, <span class="at">y =</span> EMPSTAT, <span class="at">weight =</span> PERWT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="co">#library(srvyr)</span></span>
<span id="cb137-2"><a href="#cb137-2" aria-hidden="true" tabindex="-1"></a><span class="co">#library(survey)</span></span>
<span id="cb137-3"><a href="#cb137-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb137-4"><a href="#cb137-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">PWSTATE2_clean =</span> <span class="fu">as_factor</span>(<span class="fu">lbl_na_if</span>(PWSTATE2, <span class="sc">~</span>.val <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb137-5"><a href="#cb137-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">inctot_decile =</span> <span class="fu">ntile</span>(INCTOT, <span class="dv">10</span>),</span>
<span id="cb137-6"><a href="#cb137-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">incwage_decile =</span> <span class="fu">ntile</span>(INCWAGE, <span class="dv">10</span>),</span>
<span id="cb137-7"><a href="#cb137-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">incearn_decile =</span><span class="fu">ntile</span>(INCEARN, <span class="dv">10</span>))  <span class="co">#adds a variable to indicate which decile an observation falls within</span></span>
<span id="cb137-8"><a href="#cb137-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-9"><a href="#cb137-9" aria-hidden="true" tabindex="-1"></a><span class="co">#attempt &lt;- svydesign(id=~row(data) , weights=data$PERWT, data=data)</span></span>
<span id="cb137-10"><a href="#cb137-10" aria-hidden="true" tabindex="-1"></a><span class="co">#a &lt;- svyquantile(design=attempt, quantiles = seq(0,1, by=0.1))</span></span>
<span id="cb137-11"><a href="#cb137-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-12"><a href="#cb137-12" aria-hidden="true" tabindex="-1"></a><span class="co">#quantile(x, probs = seq(0, 1, 1/10))    # Deciles</span></span>
<span id="cb137-13"><a href="#cb137-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-14"><a href="#cb137-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCEARN))</span>
<span id="cb137-15"><a href="#cb137-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-16"><a href="#cb137-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-17"><a href="#cb137-17" aria-hidden="true" tabindex="-1"></a><span class="co"># weighted_breaksummary &lt;- data %&gt;% </span></span>
<span id="cb137-18"><a href="#cb137-18" aria-hidden="true" tabindex="-1"></a><span class="co">#   #srvyr::as_survey(weights = PERWT) %&gt;%</span></span>
<span id="cb137-19"><a href="#cb137-19" aria-hidden="true" tabindex="-1"></a><span class="co">#   group_by(incearn_decile) %&gt;%</span></span>
<span id="cb137-20"><a href="#cb137-20" aria-hidden="true" tabindex="-1"></a><span class="co">#   summarize(decile_min = min(INCEARN),</span></span>
<span id="cb137-21"><a href="#cb137-21" aria-hidden="true" tabindex="-1"></a><span class="co">#             decile_max = max(INCEARN)</span></span>
<span id="cb137-22"><a href="#cb137-22" aria-hidden="true" tabindex="-1"></a><span class="co">#             ) </span></span>
<span id="cb137-23"><a href="#cb137-23" aria-hidden="true" tabindex="-1"></a><span class="co"># weighted_breaksummary # not actually weighted yet because I used incearn_decile which was created without weighing the data...</span></span>
<span id="cb137-24"><a href="#cb137-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-25"><a href="#cb137-25" aria-hidden="true" tabindex="-1"></a>unweighted_breaksummary <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb137-26"><a href="#cb137-26" aria-hidden="true" tabindex="-1"></a>  <span class="co">#srvyr::as_survey(weights = c(PERWT)) %&gt;%</span></span>
<span id="cb137-27"><a href="#cb137-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(incearn_decile) <span class="sc">%&gt;%</span></span>
<span id="cb137-28"><a href="#cb137-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">decile_min =</span> <span class="fu">min</span>(INCEARN),</span>
<span id="cb137-29"><a href="#cb137-29" aria-hidden="true" tabindex="-1"></a>            <span class="at">decile_max =</span> <span class="fu">max</span>(INCEARN)</span>
<span id="cb137-30"><a href="#cb137-30" aria-hidden="true" tabindex="-1"></a>            ) </span>
<span id="cb137-31"><a href="#cb137-31" aria-hidden="true" tabindex="-1"></a>unweighted_breaksummary <span class="co"># NOT WEIGHTED!!!!</span></span>
<span id="cb137-32"><a href="#cb137-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-33"><a href="#cb137-33" aria-hidden="true" tabindex="-1"></a><span class="co"># histogram of total income</span></span>
<span id="cb137-34"><a href="#cb137-34" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>INCEARN, <span class="at">breaks =</span> <span class="dv">60</span>) <span class="co"># unweighted</span></span>
<span id="cb137-35"><a href="#cb137-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-36"><a href="#cb137-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-37"><a href="#cb137-37" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb137-38"><a href="#cb137-38" aria-hidden="true" tabindex="-1"></a> <span class="co"># filter (INCTOT &lt; 400000) %&gt;% </span></span>
<span id="cb137-39"><a href="#cb137-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>INCEARN)) <span class="sc">+</span> </span>
<span id="cb137-40"><a href="#cb137-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span>  <span class="dv">60</span>) <span class="sc">+</span> </span>
<span id="cb137-41"><a href="#cb137-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> <span class="fu">label_dollar</span>())</span>
<span id="cb137-42"><a href="#cb137-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-43"><a href="#cb137-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-44"><a href="#cb137-44" aria-hidden="true" tabindex="-1"></a><span class="fu">topline</span>(data, incearn_decile, <span class="at">weight =</span> PERWT)</span>
<span id="cb137-45"><a href="#cb137-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-46"><a href="#cb137-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-47"><a href="#cb137-47" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>decile <span class="ot">&lt;-</span> <span class="fu">ntile</span>(data<span class="sc">$</span>INCEARN, <span class="dv">10</span>)</span>
<span id="cb137-48"><a href="#cb137-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-49"><a href="#cb137-49" aria-hidden="true" tabindex="-1"></a><span class="co"># from weights() package</span></span>
<span id="cb137-50"><a href="#cb137-50" aria-hidden="true" tabindex="-1"></a><span class="fu">wtd.hist</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCEARN), <span class="at">breaks =</span> <span class="dv">40</span>, <span class="at">weight =</span> data<span class="sc">$</span>PERWT)</span>
<span id="cb137-51"><a href="#cb137-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-52"><a href="#cb137-52" aria-hidden="true" tabindex="-1"></a><span class="fu">wtd.hist</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>INCEARN), <span class="at">weight =</span> data<span class="sc">$</span>PERWT)</span>
<span id="cb137-53"><a href="#cb137-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-54"><a href="#cb137-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-55"><a href="#cb137-55" aria-hidden="true" tabindex="-1"></a><span class="co"># data_svy = svydesign(~1, #no clusters</span></span>
<span id="cb137-56"><a href="#cb137-56" aria-hidden="true" tabindex="-1"></a><span class="co">#                      data = data, </span></span>
<span id="cb137-57"><a href="#cb137-57" aria-hidden="true" tabindex="-1"></a><span class="co">#                      weight=~PERWT)</span></span>
<span id="cb137-58"><a href="#cb137-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-59"><a href="#cb137-59" aria-hidden="true" tabindex="-1"></a>  <span class="co">#svyquantile(~INCTOT,data_svy, </span></span>
<span id="cb137-60"><a href="#cb137-60" aria-hidden="true" tabindex="-1"></a>   <span class="co">#                          quantiles=seq(0.1, 0.9, 0.1))</span></span>
<span id="cb137-61"><a href="#cb137-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-62"><a href="#cb137-62" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x=</span>INCEARN)) <span class="sc">+</span> </span>
<span id="cb137-63"><a href="#cb137-63" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span>  <span class="dv">30</span>) <span class="sc">+</span> </span>
<span id="cb137-64"><a href="#cb137-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> <span class="fu">label_dollar</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="co">#telework csv uses data from Dingle and Nieman</span></span>
<span id="cb138-2"><a href="#cb138-2" aria-hidden="true" tabindex="-1"></a><span class="co"># https://github.com/jdingel/DingelNeiman-workathome/blob/master/occ_manual_scores/input/Teleworkable_BNJDopinion.csv</span></span>
<span id="cb138-3"><a href="#cb138-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb138-4"><a href="#cb138-4" aria-hidden="true" tabindex="-1"></a>telework<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"teleworkable2010_v2.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1810 Columns: 5
-- Column specification --------------------------------------------------------
Delimiter: ","
chr (3): onetsoc_6digits, major_code_label, major_code_2digits
dbl (2): Count of teleworkable, teleworkable

i Use `spec()` to retrieve the full column specification for this data.
i Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="co">#telework&lt;- read_csv("teleworkable2010.csv")</span></span>
<span id="cb140-2"><a href="#cb140-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb140-3"><a href="#cb140-3" aria-hidden="true" tabindex="-1"></a><span class="co"># causes problems for any occupation code that has XX in it!! </span></span>
<span id="cb140-4"><a href="#cb140-4" aria-hidden="true" tabindex="-1"></a><span class="co">#data_labforce$OCCSOC_num &lt;- as.numeric(data_labforce$OCCSOC)</span></span>
<span id="cb140-5"><a href="#cb140-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb140-6"><a href="#cb140-6" aria-hidden="true" tabindex="-1"></a>innerjoined<span class="ot">&lt;-</span><span class="fu">inner_join</span>(data_labforce, telework, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"OCCSOC"</span><span class="ot">=</span> <span class="st">"onetsoc_6digits"</span>))</span>
<span id="cb140-7"><a href="#cb140-7" aria-hidden="true" tabindex="-1"></a><span class="co"># ___ obs in innerjoin</span></span>
<span id="cb140-8"><a href="#cb140-8" aria-hidden="true" tabindex="-1"></a><span class="co"># __ obs after updating teleworkable2010 file with broader 5digit codes that 6digit 0</span></span>
<span id="cb140-9"><a href="#cb140-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb140-10"><a href="#cb140-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 312350 obs after adding 5digitsX and 4digitsXX codes to teleworkable.</span></span>
<span id="cb140-11"><a href="#cb140-11" aria-hidden="true" tabindex="-1"></a><span class="co"># teleworkable values are an average of occupations with same first 5 digits and first 4 digits. </span></span>
<span id="cb140-12"><a href="#cb140-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb140-13"><a href="#cb140-13" aria-hidden="true" tabindex="-1"></a>leftjoined<span class="ot">&lt;-</span><span class="fu">left_join</span>(data_labforce, telework, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"OCCSOC"</span><span class="ot">=</span> <span class="st">"onetsoc_6digits"</span>))</span>
<span id="cb140-14"><a href="#cb140-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb140-15"><a href="#cb140-15" aria-hidden="true" tabindex="-1"></a><span class="co">#innerjoined&lt;-inner_join(data_labforce, telework, by = c("OCCSOC_num"= "BroadGroupCode"))</span></span>
<span id="cb140-16"><a href="#cb140-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb140-17"><a href="#cb140-17" aria-hidden="true" tabindex="-1"></a><span class="co">#leftjoined&lt;-left_join(data_labforce, telework, by = c("OCCSOC_num"= "BroadGroupCode"))</span></span>
<span id="cb140-18"><a href="#cb140-18" aria-hidden="true" tabindex="-1"></a><span class="co"># keeps all observations in data 2 even if they don't match</span></span>
<span id="cb140-19"><a href="#cb140-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb140-20"><a href="#cb140-20" aria-hidden="true" tabindex="-1"></a><span class="co">#antijoin &lt;-anti_join(data_labforce, telework, by = c("OCCSOC_num"= "onetsoc_6digits"))</span></span>
<span id="cb140-21"><a href="#cb140-21" aria-hidden="true" tabindex="-1"></a><span class="co"># 158525. Many were aggregated to 5digits with 6digit as 0.</span></span>
<span id="cb140-22"><a href="#cb140-22" aria-hidden="true" tabindex="-1"></a><span class="co"># 91403 obs after updating teleworkable file to 5digits with 6digit as 0</span></span>
<span id="cb140-23"><a href="#cb140-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb140-24"><a href="#cb140-24" aria-hidden="true" tabindex="-1"></a><span class="co">#couldnt use _num version due to XX in values.</span></span>
<span id="cb140-25"><a href="#cb140-25" aria-hidden="true" tabindex="-1"></a>antijoin <span class="ot">&lt;-</span><span class="fu">anti_join</span>(data_labforce, telework, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"OCCSOC"</span><span class="ot">=</span> <span class="st">"onetsoc_6digits"</span>))</span>
<span id="cb140-26"><a href="#cb140-26" aria-hidden="true" tabindex="-1"></a><span class="co"># 50,584 obs after adding 5digitsX and 4digitsXX and 5digits with sixth as 0 to csv file</span></span>
<span id="cb140-27"><a href="#cb140-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb140-28"><a href="#cb140-28" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(antijoin<span class="sc">$</span>OCCSOC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "291210" "254022" "211019" "537065" "151252" "211029" "131082" "514XXX"
 [9] "1721YY" "311131" "251000" "299000" "413091" "533054" "353023" "292042"
[17] "272099" "533051" "291292" "533052" "151211" "519160" "311121" "292072"
[25] "31113X" "151299" "151251" "151253" "151230" "273092" "472XXX" "311122"
[33] "1940YY" "531000" "391000" "419099" "399099" "439XXX" "151244" "253041"
[41] "151241" "151254" "15124X" "151212" "533053" "513099" "273023" "291240"
[49] "212099" "292043" "434XXX" "434YYY" "559830" "113012" "291291" "113013"
[57] "533099" "273099" "151255" "432099" "195010" "4750YY" "291299" "193034"
[65] "232099" "359099" "339094" "475032" "151221" "193033" "453031" "272091"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="co"># down to 73 after adding 5digitsX and 4digitsXX and 5digits with sixth as 0 to csv file</span></span>
<span id="cb142-2"><a href="#cb142-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb142-3"><a href="#cb142-3" aria-hidden="true" tabindex="-1"></a><span class="co">#table(joined$Teleworkable)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="xiaoyans-merging-notes" class="level2">
<h2 class="anchored" data-anchor-id="xiaoyans-merging-notes">Xiaoyan’s Merging Notes</h2>
<p>Code chunk below is my attempt to manually recode items that didn’t match. I think I have an excel file of OCCSOC codes that should match almost completely.</p>
<p><em>Double check</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a>data_labforce021 <span class="sc">%&gt;%</span> </span>
<span id="cb143-2"><a href="#cb143-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(OCCSOC <span class="sc">&gt;</span><span class="dv">0</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb143-3"><a href="#cb143-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">telworkable =</span> <span class="fu">case_when</span>(</span>
<span id="cb143-4"><a href="#cb143-4" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"113013"</span> <span class="sc">~</span> ,</span>
<span id="cb143-5"><a href="#cb143-5" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"131081"</span> <span class="sc">~</span> ,</span>
<span id="cb143-6"><a href="#cb143-6" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"151255"</span> <span class="sc">~</span> ,</span>
<span id="cb143-7"><a href="#cb143-7" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"195010"</span> <span class="sc">~</span> ,</span>
<span id="cb143-8"><a href="#cb143-8" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"211019"</span> <span class="sc">~</span> ,</span>
<span id="cb143-9"><a href="#cb143-9" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"211029"</span> <span class="sc">~</span> ,    </span>
<span id="cb143-10"><a href="#cb143-10" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"211092"</span> <span class="sc">~</span> ,</span>
<span id="cb143-11"><a href="#cb143-11" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"211093"</span> <span class="sc">~</span> ,</span>
<span id="cb143-12"><a href="#cb143-12" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"212099"</span> <span class="sc">~</span> ,</span>
<span id="cb143-13"><a href="#cb143-13" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"232099"</span> <span class="sc">~</span> ,</span>
<span id="cb143-14"><a href="#cb143-14" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"2504022"</span> <span class="sc">~</span> <span class="st">"0"</span>, <span class="co"># libararians and media collections specialists. </span></span>
<span id="cb143-15"><a href="#cb143-15" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"272091"</span> <span class="sc">~</span> , <span class="co"># disc jockets. Was 272099</span></span>
<span id="cb143-16"><a href="#cb143-16" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"272099"</span> <span class="sc">~</span> <span class="st">"RECODED"</span>,</span>
<span id="cb143-17"><a href="#cb143-17" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"273092"</span> <span class="sc">~</span>  <span class="st">"1"</span>, <span class="co">#court reporters and captioners </span></span>
<span id="cb143-18"><a href="#cb143-18" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"273099"</span> <span class="sc">~</span> <span class="st">"1"</span>, <span class="co"># media and comunication workers, all other</span></span>
<span id="cb143-19"><a href="#cb143-19" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"311122"</span> <span class="sc">~</span> <span class="st">"0"</span>,   <span class="co"># personal care aids</span></span>
<span id="cb143-20"><a href="#cb143-20" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"331090"</span> <span class="sc">~</span> <span class="st">"0"</span>,    <span class="co"># healthcare and support specialists </span></span>
<span id="cb143-21"><a href="#cb143-21" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"339094"</span> <span class="sc">~</span> ,    </span>
<span id="cb143-22"><a href="#cb143-22" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"359099"</span> <span class="sc">~</span> ,    </span>
<span id="cb143-23"><a href="#cb143-23" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"413091"</span> <span class="sc">~</span> <span class="st">"0"</span>,</span>
<span id="cb143-24"><a href="#cb143-24" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"419099"</span> <span class="sc">~</span>  <span class="st">"0"</span>, <span class="co"># sales and related workers all other</span></span>
<span id="cb143-25"><a href="#cb143-25" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"432099"</span> <span class="sc">~</span> <span class="st">"0.5"</span>, <span class="co"># communications equipment operators, all other</span></span>
<span id="cb143-26"><a href="#cb143-26" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"4330XX"</span> <span class="sc">~</span> <span class="st">"0.5"</span>, <span class="co"># 43 is office and admin support</span></span>
<span id="cb143-27"><a href="#cb143-27" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"513099"</span> <span class="sc">~</span> <span class="st">"0"</span>, <span class="co">#food processing workers</span></span>
<span id="cb143-28"><a href="#cb143-28" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"533099"</span> <span class="sc">~</span>  <span class="st">"0"</span>, <span class="co"># motor vehicle operators</span></span>
<span id="cb143-29"><a href="#cb143-29" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"537065"</span> <span class="sc">~</span> <span class="st">"0"</span>, <span class="co"># stockers and order fillers</span></span>
<span id="cb143-30"><a href="#cb143-30" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"551010"</span> <span class="sc">~</span> <span class="st">"0"</span>, <span class="co"># miltary </span></span>
<span id="cb143-31"><a href="#cb143-31" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"552020"</span> <span class="sc">~</span> <span class="st">"0"</span>, <span class="co"># military</span></span>
<span id="cb143-32"><a href="#cb143-32" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"553010"</span> <span class="sc">~</span> <span class="st">"0"</span>, <span class="co"># military</span></span>
<span id="cb143-33"><a href="#cb143-33" aria-hidden="true" tabindex="-1"></a>    OCCSOC <span class="sc">==</span> <span class="st">"559830"</span> <span class="sc">~</span> <span class="st">"0"</span>, <span class="co"># military</span></span>
<span id="cb143-34"><a href="#cb143-34" aria-hidden="true" tabindex="-1"></a><span class="cn">TRUE</span> <span class="sc">~</span> <span class="fu">as.character</span>(OCCSOC))</span>
<span id="cb143-35"><a href="#cb143-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb143-36"><a href="#cb143-36" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>****merge****</p>
<p>merge m:1 occsoc using “/Users/xiaoyanhu/Desktop/crosswalk.dta”</p>
<p>*IL has but DN no: 29, merge==2</p>
<p>*113013 Facilities Managers</p>
<p>*131082 Project Management Specialists</p>
<p>*151255 Web And Digital Interface Designers</p>
<p>*195010 Occupational Health And Safety Specialists And Technicians</p>
<p>*211019 Counselors, All Other</p>
<p>*211029 Social Workers All Other</p>
<p>*211092 Probation Officers and Correctional Treatment Specialists</p>
<p>*211093 Social and Human Service Assistants</p>
<p>*212099 Religious Workers, All Other</p>
<p>*232099 Legal Support Workers, All Other</p>
<p>*272091 Disc Jockeys, Except Radio</p>
<p>*272099 Entertainers and Performers, Sports and Related Workers, All Other</p>
<p>*273092 Court Reporters And Simultaneous Captioners</p>
<p>*273099 Media And Communications Workers, All Other</p>
<p>*311122 Personal Care Aides</p>
<p>*331090 Miscellaneous First-Line Supervisors, Protective Service Workers</p>
<p>*339094 School Bus Monitors</p>
<p>*359099 Food Preparation and Serving Related Workers, All Other</p>
<p>*413091 Sales Representatives Of Services, Except Advertising, Insurance, Financial Services, And Travel</p>
<p>*419099 Sales and Related Workers, All Other</p>
<p>*432099 Communications Equipment Operators, All Other</p>
<p>*4330XX Other Financial Clerks</p>
<p>*513099 Food Processing Workers, All&nbsp;Other</p>
<p>*533099 Motor Vehicle Operators, All Other</p>
<p>*537065 Stockers And Order Fillers</p>
<p>*551010 Military Officer Special and Tactical Operations Leaders</p>
<p>*552010 First-Line Enlisted Military Supervisors</p>
<p>*553010 Military Enlisted Tactical Operations and Air/Weapons Specialists and Crew Members</p>
<p>*559830 Military, Rank Not Specified</p>
<p>*DN has but IL no: 7, merge==1</p>
<p>** AWM - These were 2010 codes that have been changed to 2018 SOC codes</p>
<p>*119061 Funeral Service Managers #Code and Title change to 119171</p>
<p>*119131 Postmasters and Mail Superintendents #Didn’t change, should have been in their file?</p>
<p>*173021 Aerospace Engineering and Operations Technicians</p>
<p>*173022 Civil Engineering Technicians</p>
<p>*232091 Court Reporters</p>
<p>*413099 Energy Brokers</p>
<p>*433041 Gaming Cage Workers</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>